### ISSUE TITLE
Clang crashes on nested lambdas with parameter packs

### ISSUE THREAD

**Issue by Taw3e8** [llvm/llvm-project#102169]
This code crashes: https://godbolt.org/z/zdGvoE6h4
```cpp
template <std::size_t N, std::size_t M>
concept C = requires {
    []<std::size_t... Is>(std::index_sequence<Is...>)
    requires requires {
        []<std::size_t... Js>(std::index_sequence<Js...>)
        requires requires { true; }
        {}(std::make_index_sequence<M>{});
    }
    {}(std::make_index_sequence<N>{});
};
```
But without the nested lambda it's fine: https://godbolt.org/z/P8svEfjYd

Some issues that seem related: https://github.com/llvm/llvm-project/issues/86361, https://github.com/llvm/llvm-project/issues/93256, https://github.com/llvm/llvm-project/issues/85667

**Comment by zyn0217** [comment]
Looks like a regression since 18.

**Comment by zyn0217** [comment]
I tested locally, and we seem to run into an infinite recursion when mangling requires expressions:


```
#5 0x00007fd5cc08098d (anonymous namespace)::CXXNameMangler::mangleExpression(clang::Expr const*, unsigned int, bool) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:4657:12
  #6 0x00007fd5cc089aa7 (anonymous namespace)::CXXNameMangler::mangleRequiresClause(clang::Expr const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:2085:1
  #7 0x00007fd5cc08c79a (anonymous namespace)::CXXNameMangler::mangleBareFunctionType(clang::FunctionProtoType const*, bool, clang::FunctionDecl const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:0:5
  #8 0x00007fd5cc071610 (anonymous namespace)::CXXNameMangler::mangleFunctionEncodingBareType(clang::FunctionDecl const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:957:1
  #9 0x00007fd5cc070c65 (anonymous namespace)::CXXNameMangler::mangleFunctionEncoding(clang::GlobalDecl) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:855:5
 #10 0x00007fd5cc08f2f0 (anonymous namespace)::CXXNameMangler::mangleLocalName(clang::GlobalDecl, llvm::SmallVector<llvm::StringRef, 4u> const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:0:7
 #11 0x00007fd5cc071909 (anonymous namespace)::CXXNameMangler::mangleNameWithAbiTags(clang::GlobalDecl, llvm::SmallVector<llvm::StringRef, 4u> const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:1090:5
 #12 0x00007fd5cc0711f1 (anonymous namespace)::CXXNameMangler::mangleName(clang::GlobalDecl) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:1042:1
 #13 0x00007fd5cc08dfed (anonymous namespace)::CXXNameMangler::mangleType(clang::TagType const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:3666:1
 #14 0x00007fd5cc07f6dd (anonymous namespace)::CXXNameMangler::mangleType(clang::RecordType const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:3663:1
 #15 0x00007fd5cc0722d5 (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) /repo/llvm-project-Build/BuildDebug/tools/clang/include/clang/AST/TypeNodes.inc:75:1
 #16 0x00007fd5cc083f05 (anonymous namespace)::CXXNameMangler::mangleExpression(clang::Expr const*, unsigned int, bool) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:5608:5
 #17 0x00007fd5cc0812c3 (anonymous namespace)::CXXNameMangler::mangleExpression(clang::Expr const*, unsigned int, bool) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:4915:28
 #18 0x00007fd5cc087883 (anonymous namespace)::CXXNameMangler::mangleRequirement(clang::SourceLocation, clang::concepts::Requirement const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:4598:9
 #19 0x00007fd5cc08375b (anonymous namespace)::CXXNameMangler::mangleExpression(clang::Expr const*, unsigned int, bool) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:5466:45
 #20 0x00007fd5cc089aa7 (anonymous namespace)::CXXNameMangler::mangleRequiresClause(clang::Expr const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:2085:1
 #21 0x00007fd5cc08c79a (anonymous namespace)::CXXNameMangler::mangleBareFunctionType(clang::FunctionProtoType const*, bool, clang::FunctionDecl const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:0:5
 #22 0x00007fd5cc071610 (anonymous namespace)::CXXNameMangler::mangleFunctionEncodingBareType(clang::FunctionDecl const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:957:1
 #23 0x00007fd5cc070c65 (anonymous namespace)::CXXNameMangler::mangleFunctionEncoding(clang::GlobalDecl) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:855:5
 #24 0x00007fd5cc08f2f0 (anonymous namespace)::CXXNameMangler::mangleLocalName(clang::GlobalDecl, llvm::SmallVector<llvm::StringRef, 4u> const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:0:7
 #25 0x00007fd5cc071909 (anonymous namespace)::CXXNameMangler::mangleNameWithAbiTags(clang::GlobalDecl, llvm::SmallVector<llvm::StringRef, 4u> const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:1090:5
 #26 0x00007fd5cc0711f1 (anonymous namespace)::CXXNameMangler::mangleName(clang::GlobalDecl) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:1042:1
 #27 0x00007fd5cc08dfed (anonymous namespace)::CXXNameMangler::mangleType(clang::TagType const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:3666:1
 #28 0x00007fd5cc07f6dd (anonymous namespace)::CXXNameMangler::mangleType(clang::RecordType const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:3663:1
 #29 0x00007fd5cc0722d5 (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) /repo/llvm-project-Build/BuildDebug/tools/clang/include/clang/AST/TypeNodes.inc:75:1
 #30 0x00007fd5cc083f05 (anonymous namespace)::CXXNameMangler::mangleExpression(clang::Expr const*, unsigned int, bool) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:5608:5
 #31 0x00007fd5cc0812c3 (anonymous namespace)::CXXNameMangler::mangleExpression(clang::Expr const*, unsigned int, bool) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:4915:28
 #32 0x00007fd5cc087883 (anonymous namespace)::CXXNameMangler::mangleRequirement(clang::SourceLocation, clang::concepts::Requirement const*) /repo/llvm-project/clang/lib/AST/ItaniumMangle.cpp:4598:9
...
```

So this is probably a duplicate of https://github.com/llvm/llvm-project/issues/70064.

**Comment by shafik** [comment]
@zyn0217 I can not get this to crash locally but I just pulled, so maybe it is fixed?!? I was trying to bisect it.

**Comment by zyn0217** [comment]
> [@zyn0217](https://github.com/zyn0217) I can not get this to crash locally but I just pulled, so maybe it is fixed?!? I was trying to bisect it.

I don't think so... Perhaps the infinite recursion is hidden by something else? (it may depend on the system behavior?) but I'm still seeing a SIGSEGV on godbolt after hitting the refresh button a few times

**Comment by hongtaihu** [comment]
https://godbolt.org/z/reW35P9oc

Seems that this issue comes back on trunk?
It does not crash on clang 22.1.0 through.
```
clang++: /root/llvm-project/llvm/tools/clang/include/clang/AST/TypeBase.h:954: const clang::ExtQualsTypeCommonBase* clang::QualType::getCommonPtr() const: Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and dumped files.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++26 <source>
1.	<source>:14:22: current parser token ')'
 #0 0x000000000441ece8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x441ece8)
 #1 0x000000000441bb94 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x441bb94)
 #2 0x000000000441c1cc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x441c1cc)
 #3 0x000000000435b1a8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x000075dec0245330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #5 0x000075dec029eb2c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x9eb2c)
 #6 0x000075dec024527e raise (/lib/x86_64-linux-gnu/libc.so.6+0x4527e)
 #7 0x000075dec02288ff abort (/lib/x86_64-linux-gnu/libc.so.6+0x288ff)
 #8 0x000075dec022881b (/lib/x86_64-linux-gnu/libc.so.6+0x2881b)
 #9 0x000075dec023b517 (/lib/x86_64-linux-gnu/libc.so.6+0x3b517)
#10 0x000000000480dad4 (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x480dad4)
#11 0x0000000007f83547 clang::NamedDecl::printNestedNameSpecifier(llvm::raw_ostream&, clang::PrintingPolicy const&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7f83547)
#12 0x00000000085d2056 (anonymous namespace)::TypePrinter::printTagType(clang::TagType const*, llvm::raw_ostream&) TypePrinter.cpp:0:0
#13 0x00000000085cfae0 (anonymous namespace)::TypePrinter::printBefore(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&) TypePrinter.cpp:0:0
#14 0x00000000085d6c2e clang::QualType::getAsStringInternal(clang::Type const*, clang::Qualifiers, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, clang::PrintingPolicy const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x85d6c2e)
#15 0x00000000085d70bd clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x85d70bd)
#16 0x0000000007da275b ConvertTypeToDiagnosticString(clang::ASTContext&, clang::QualType, llvm::ArrayRef<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>>, llvm::ArrayRef<long>) ASTDiagnostic.cpp:0:0
#17 0x0000000007da80da clang::FormatASTNodeDiagnosticArgument(clang::DiagnosticsEngine::ArgumentKind, long, llvm::StringRef, llvm::StringRef, llvm::ArrayRef<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>>, llvm::SmallVectorImpl<char>&, void*, llvm::ArrayRef<long>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7da80da)
#18 0x00000000047d0c7e clang::Diagnostic::FormatDiagnostic(char const*, char const*, llvm::SmallVectorImpl<char>&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47d0c7e)
#19 0x00000000078db565 createSubstDiag(clang::Sema&, clang::sema::TemplateDeductionInfo&, llvm::function_ref<void (llvm::raw_ostream&)>) SemaTemplateInstantiate.cpp:0:0
#20 0x0000000007910975 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformRequiresExpr(clang::RequiresExpr*) SemaTemplateInstantiate.cpp:0:0
#21 0x00000000078e6915 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#22 0x00000000078e5cb8 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformLambdaExpr(clang::LambdaExpr*) SemaTemplateInstantiate.cpp:0:0
#23 0x00000000078e6be9 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#24 0x000000000790a596 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) SemaTemplateInstantiate.cpp:0:0
#25 0x00000000078e641a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#26 0x0000000007910929 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformRequiresExpr(clang::RequiresExpr*) SemaTemplateInstantiate.cpp:0:0
#27 0x00000000078e6915 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#28 0x00000000078f0d2e clang::Sema::SubstConstraintExpr(clang::Expr*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x78f0d2e)
#29 0x00000000070c75e5 (anonymous namespace)::ConstraintSatisfactionChecker::Evaluate(clang::AtomicConstraint const&, clang::MultiLevelTemplateArgumentList const&) SemaConcept.cpp:0:0
#30 0x00000000070c97e0 (anonymous namespace)::ConstraintSatisfactionChecker::Evaluate(clang::ConceptIdConstraint const&, clang::MultiLevelTemplateArgumentList const&) SemaConcept.cpp:0:0
#31 0x00000000070cbf87 CheckConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::AssociatedConstraint>, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&, clang::Expr**, clang::ConceptReference const*) SemaConcept.cpp:0:0
#32 0x00000000070cc7dc clang::Sema::CheckConstraintSatisfaction(llvm::PointerUnion<clang::NamedDecl const*, clang::concepts::NestedRequirement const*>, llvm::ArrayRef<clang::AssociatedConstraint>, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&, clang::ConceptReference const*, clang::Expr**) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x70cc7dc)
#33 0x00000000077b5660 clang::Sema::CheckConceptTemplateId(clang::CXXScopeSpec const&, clang::SourceLocation, clang::DeclarationNameInfo const&, clang::NamedDecl*, clang::TemplateDecl*, clang::TemplateArgumentListInfo const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x77b5660)
#34 0x00000000077bcecd clang::Sema::BuildTemplateIdExpr(clang::CXXScopeSpec const&, clang::SourceLocation, clang::LookupResult&, bool, clang::TemplateArgumentListInfo const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x77bcecd)
#35 0x00000000072e57e8 clang::Sema::ActOnIdExpression(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, bool, bool, clang::CorrectionCandidateCallback*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x72e57e8)
#36 0x0000000006decb75 clang::Parser::tryParseCXXIdExpression(clang::CXXScopeSpec&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6decb75)
#37 0x0000000006decefe clang::Parser::ParseCXXIdExpression(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6decefe)
#38 0x0000000006dcb279 clang::Parser::ParseCastExpression(clang::CastParseKind, bool, bool&, clang::TypoCorrectionTypeBehavior, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dcb279)
#39 0x0000000006dca760 clang::Parser::ParseCastExpression(clang::CastParseKind, bool, bool&, clang::TypoCorrectionTypeBehavior, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dca760)
#40 0x0000000006dd789e clang::Parser::ParseConstantExpressionInExprEvalContext(clang::TypoCorrectionTypeBehavior) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dd789e)
#41 0x0000000006dae6f6 clang::Parser::ParseStaticAssertDeclaration(clang::SourceLocation&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dae6f6)
#42 0x0000000006da6086 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6da6086)
#43 0x0000000006d5c970 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d5c970)
#44 0x0000000006d5d8a5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d5d8a5)
#45 0x0000000006d3add2 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d3add2)
#46 0x0000000004f20e58 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f20e58)
#47 0x000000000524e5d8 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x524e5d8)
#48 0x00000000051db19d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x51db19d)
#49 0x0000000005322f6d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5322f6d)
#50 0x0000000000dae66c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdae66c)
#51 0x0000000000da528a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#52 0x0000000000da540d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#53 0x0000000004f98919 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#54 0x000000000435b5e4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x435b5e4)
#55 0x0000000004f99485 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#56 0x0000000004f51732 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f51732)
#57 0x0000000004f55f67 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f55f67)
#58 0x0000000004f604c5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f604c5)
#59 0x0000000000daab6a clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdaab6a)
#60 0x0000000000cc659a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcc659a)
#61 0x000075dec022a1ca (/lib/x86_64-linux-gnu/libc.so.6+0x2a1ca)
#62 0x000075dec022a28b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28b)
#63 0x0000000000da4c35 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda4c35)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 134
```
