### ISSUE TITLE
Weird link messages on macOS Sequoia

### ISSUE THREAD

**Issue by ncihnegn** [llvm/llvm-project#109549]
```
Run Build Command(s): /usr/local/bin/ninja -v
[1/1] : && /usr/local/opt/llvm/bin/clang++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -flto -fsanitize=address,undefined CMakeFiles/p1.dir/src/p1.cpp.o -o p1   lib__cmake_cxx26.a && :
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/swift/libswiftCore.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/swift/libswiftCore.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Security.framework/Versions/A/Security is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Security.framework/Versions/A/Security is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Security.framework/Versions/A/Security is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Security.framework/Versions/A/Security is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreAnalytics.framework/Versions/A/CoreAnalytics is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreAnalytics.framework/Versions/A/CoreAnalytics is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/NetworkServiceProxy.framework/Versions/A/NetworkServiceProxy is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/NetworkServiceProxy.framework/Versions/A/NetworkServiceProxy is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Network.framework/Versions/A/Network is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/swift/libswift_Concurrency.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/swift/libswift_Concurrency.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/LoggingSupport.framework/Versions/A/LoggingSupport is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/LoggingSupport.framework/Versions/A/LoggingSupport is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/libcupolicy.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/libcupolicy.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Metal.framework/Versions/A/Metal is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Metal.framework/Versions/A/Metal is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Metal.framework/Versions/A/Metal is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Metal.framework/Versions/A/Metal is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/libutil.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/libutil.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/libutil.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/libutil.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/AccelerateGPU.framework/Versions/A/AccelerateGPU is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /usr/lib/libate.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/libllvm-flatbuffers.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/libllvm-flatbuffers.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/libllvm-flatbuffers.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/libllvm-flatbuffers.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/libGPUCompilerUtils.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/libGPUCompilerUtils.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSCore.framework/Versions/A/MPSCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSCore.framework/Versions/A/MPSCore is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSImage.framework/Versions/A/MPSImage is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSImage.framework/Versions/A/MPSImage is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdaPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnwmSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray is being set to 0xBAD4007.
dyld[55123]: symbol '__ZnamSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray is being set to 0xBAD4007.
dyld[55123]: symbol '__ZdlPvSt19__type_descriptor_t' missing from root that overrides /usr/lib/libc++abi.dylib. Use of that symbol in /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray is being set to 0xBAD4007.
...
```

Totally 326 error messages of the same type.

**Comment by mastroalex** [comment]
Same problem, also with other software. Any idea?

**Comment by dbabokin** [comment]
Note that these are only 4 different symbols in the output (I have the same on my machine):
```
'__ZdaPvSt19__type_descriptor_t'
'__ZdlPvSt19__type_descriptor_t'
'__ZnamSt19__type_descriptor_t'
'__ZnwmSt19__type_descriptor_t'
```

And these dymbols are:
```c++
operator delete[](void*, std::__type_descriptor_t)
operator delete(void*, std::__type_descriptor_t)
operator new[](unsigned long, std::__type_descriptor_t)
operator new(unsigned long, std::__type_descriptor_t)
```

**Comment by dbabokin** [comment]
I'm wondering if it's related to https://github.com/llvm/llvm-project/issues/78860? Though in my case I build both `libcxx` and `libcxxabi` together with the compiler.

**Comment by hanickadot** [comment]
I ran into this issue to when trying to run libcxx's tests.

**Comment by hanickadot** [comment]
I'm configuring LLVM on my Sequia mac:

```
#!/usr/bin/env bash

MACOS_SDK=`xcrun --show-sdk-path`

cmake -B build -S llvm-project/llvm \
  -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DCMAKE_BUILD_TYPE=Debug \
  -DLLVM_OPTIMIZED_TABLEGEN=ON \
  -DLLVM_TARGETS_TO_BUILD=AArch64 \
  -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind;compiler-rt" \
  -DLLVM_ENABLE_LIBCXX=ON \
  -DLIBCXXABI_ENABLE_SHARED=ON \
  -DLLVM_INCLUDE_TESTS=ON \
  -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
  -DDEFAULT_SYSROOT=${MACOS_SDK}
```

**Comment by ldionne** [comment]
@ncihnegn @dbabokin What was the command that you folks used to configure and build?

**Comment by ldionne** [comment]
Actually, this configuration reproduces the same issues as above for me:

```
cmake -B build/repro-link-error -S llvm \
  -GNinja \
  -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_OPTIMIZED_TABLEGEN=ON \
  -DLLVM_TARGETS_TO_BUILD=Native \
  -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind;compiler-rt" \
  -DLLVM_ENABLE_LIBCXX=ON \
  -DLIBCXXABI_ENABLE_SHARED=ON \
  -DLLVM_INCLUDE_TESTS=ON \
  -DDEFAULT_SYSROOT=${MACOS_SDK}
```

With @hanickadot 's configuration (which adds `LIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON`), I get a slightly different error.

**Comment by ldionne** [comment]
I narrowed it down to this:

```
/usr/bin/ld -lto_library $PWD/build/repro-link-error/lib/libLTO.dylib -dynamic -arch arm64 -platform_version macos 15.0.0 15.0.0
```

Whenever `-lto_library` points to something within `build/repro-link-error/lib`, we get that error. So it looks like the linker itself (or whatever the linker is spawning for LTO) is attempting to use the just-built libc++ instead of the system-provided libc++, and that doesn't work (it can't work because upstream libc++ can't replace the system-provided libc++ out-of-the-box).

**Comment by ldionne** [comment]
Tagging with LTO: can someone familiar with LTO jump in? Why does the linker start trying to load the just-built libc++ and run using it?

**Comment by dbabokin** [comment]
> @ncihnegn @dbabokin What was the command that you folks used to configure and build?

Here's my config line:
```
cmake -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  \
      -DCMAKE_INSTALL_PREFIX=/Users/user/llvm/bin-trunk \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
      -DLLVM_ENABLE_PROJECTS="clang"  \
      -DLLVM_ENABLE_ASSERTIONS=ON  \
      -DLLVM_INSTALL_UTILS=ON  \
      -DDEFAULT_SYSROOT=`xcrun --show-sdk-path`  \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0  \
      -DLLVM_ENABLE_ZLIB=OFF \
      -DLLVM_ENABLE_ZSTD=OFF \
      -DLLVM_TARGETS_TO_BUILD=AArch64\;ARM\;X86 \
      -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly \
      ../llvm-trunk/llvm
```

**Comment by hanickadot** [comment]
The error happened somewhere between just recently and 8th July, I have some builds from that day and they do work okay.

**Comment by duddie** [comment]
I had the same messages after upgrade to Sequoia. My problem was that I finally isolated with clang19 that clang was calling /usr/bin/ld instead of my $(TOOLCHAIN)/bin/ld and /usr/bin/ld was not compatible with libs in my own built clang.
Solution to my problem was by adding -fuse-ld=lld to my LDFLAGS. All problems gone.

**Comment by dbabokin** [comment]
`lld` is not a standard linker available in the system, so it needs to be either installed separately (for example, through `brew`), or built as part of LLVM toolchain and used by for second iteration of LLVM built, right? That might be a workaround, but something if off with standard linker and it's not good.

**Comment by hanickadot** [comment]
It's not problem with system linker, but missing symbols in libraries. Using alternative linker is workaround. If you use few month old LLVM, you can link correctly on sequoia. I wish I had capacity to bisect when exactly the issue started.

**Comment by duddie** [comment]
> It's not problem with system linker, but missing symbols in libraries. Using alternative linker is workaround. If you use few month old LLVM, you can link correctly on sequoia. I wish I had capacity to bisect when exactly the issue started.

I know it was working ok with macOS 14 using clang 17.
After upgrade to macOS 15 the issue started for me (still with clang17) but the build was ok and fully working despite tons of warning of missing symbols.
After upgrading clang from 17 to 19 on macOS 15 I could not build anymore because /usr/bin/ld was just throwing "Abort Error 6".

**Comment by cachemeifyoucan** [comment]
> Tagging with LTO: can someone familiar with LTO jump in? Why does the linker start trying to load the just-built libc++ and run using it?

I don't think this is related to LTO at all. Are you sure it is the `-lto_library` option that is making the difference? My guess is that the build is somehow setting the `DYLD_LIBRARY_PATH` to a directory that contains just built libcxx/libcxxabi, that is incompatible with the system.

The error message is probably not even from the launch of clang/ld, it is from `xcrun` because I don't think clang and linker has those dylibs dependencies. `/usr/bin/ld` is just a shim on macOS that calls `xcrun` to invoke the linker in the toolchain. The CMake configuration in LLVM should have done the right thing to resolve to the actual compiler/linker in the toolchain, not the binary in `/usr/bin` directory. This is a cmake configuration problem that is probably from some user error for unsupported setup. I will try clean up and reconfigure, if still not working, try share your system configuration. Make sure `xcrun -f clang` is showing the compiler you are using.

**Comment by cachemeifyoucan** [comment]
Ah, I think I know what is happening now. This is an unfortunate interaction I think. This is my guess for the situation:
* Later Xcode has a new linker, which supports `-lto_library` in a different way than old ld64. It relaunches itself using DYLD_LIBRARY_PATH that contains libLTO (thus that path probably also contains just built libcxx if you built that).
* During the relaunch, the linker (and maybe libLTO) was built with a libcxx that has different libcxx that has incompatible ABI (in some cases) but that is probably not the same error message as described in the bug report. The linker invocation in the bug report is probably using an option that is not supported by the new linker, thus it is doing a linker fallback to ld64. This process involves another linker re-exec that involves searching for ld64 using `xcrun`, which is going to hit that all the more complicated errors in more dependency libraries.

**Comment by dbabokin** [comment]
> After upgrading clang from 17 to 19 on macOS 15 I could not build anymore because /usr/bin/ld was just throwing "Abort Error 6".

For me the behavior is consistently same for any clang version. I checked all major versions starting 16.0 to current trunk. I build clang manually, I don't use (or build) `lld`, just use the system linker.

And the behavior is multiple warnings, which are annoying, but do not seem to be harmful.

I tried building clang with `lld` (which I installed from `brew`) and this yield in `Abort trap: 6` problem:
```
    dyld[81330]: Symbol not found: ___cxa_demangle
      Referenced from: <FDE9B676-8FF7-3D2F-B75C-B230CB71A4E6> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
      Expected in:     <4C4C44CE-5555-3144-A1FC-FE9BF0A4FE37> /Users/dbabokin/llvm/bin-trunk_temp/lib/libc++.1.0.dylib
    clang: error: unable to execute command: Abort trap: 6
    clang: error: linker command failed due to signal (use -v to see invocation)
    make[1]: *** [cmTC_db1d9] Error 1
    make: *** [cmTC_db1d9/fast] Error 2
```

So, `lld` is not solving the problem for me, but makes it worse.

One other thought - during clang build on macOS there are many of the following warnings: `ld: warning: -undefined suppress is deprecated`. They are there for quite some time and everyone just ignored them, they are nothing new. I'm wondering if they have anything with this problem that we have with `dyld` now?

**Comment by cachemeifyoucan** [comment]
> So, lld is not solving the problem for me, but makes it worse.

The suggestion is to use lld to build llvm from the first place (you need to install a version of lld before you build). Or you can turn off LTO for now which should resolve the problem.

I don't think we can effectively change the behavior of the system linker, so the only thing we can probably investigate is why the libcxx/libcxxabi build from open source llvm has a different ABI from macOS system libcxx.

**Comment by dbabokin** [comment]
Speaking about `-lto_library`, AFAIK, I don't use it - i.e. I build clang with the following options:
```
cmake -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  \
      -DCMAKE_INSTALL_PREFIX=/Users/user/llvm/bin-trunk \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
      -DLLVM_ENABLE_PROJECTS="clang"  \
      -DLLVM_ENABLE_ASSERTIONS=ON  \
      -DLLVM_INSTALL_UTILS=ON  \
      -DDEFAULT_SYSROOT=`xcrun --show-sdk-path`  \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0  \
      -DLLVM_ENABLE_ZLIB=OFF \
      -DLLVM_ENABLE_ZSTD=OFF \
      -DLLVM_TARGETS_TO_BUILD=AArch64\;ARM\;X86 \
      -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly \
      ../llvm-trunk/llvm
```
which seem to not trigger LTO build. Also when invoking clang I don't use LTO. Here's an example of invocation that triggers warnings:
```
/Users/dbabokin/llvm/bin-19.1/bin/clang++ -O3  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -mmacosx-version-min=11.0 CMakeFiles/check_isa.dir/tools/check_isa.cpp.o -o bin/check_isa
```

**Comment by cachemeifyoucan** [comment]
I guess clang-driver will add `-lto_library` all the time so ignore the suggestion to turn off LTO.

Can you delete the libcxx/libcxxabi from /Users/dbabokin/llvm/bin-19.1/lib? That should fix the issue but it is an unfortunate workaround.

**Comment by dbabokin** [comment]
> Can you delete the libcxx/libcxxabi from /Users/dbabokin/llvm/bin-19.1/lib? That should fix the issue but it is an unfortunate workaround.

I've built LLVM without libcxx/libcxxabi and the `dyld` warnings are gone.

> The suggestion is to use lld to build llvm from the first place (you need to install a version of lld plus entire matching toolchain before you build). Or you can turn off LTO for now which should resolve the problem.

That's exactly what I did - I installed `lld` through `brew`, added `-DLLVM_USE_LINKER=lld` to my LLVM configuration and built it. And I got the clang, which was not functional - producing `Abort trap: 6` error.

**Comment by ldionne** [comment]
> why the libcxx/libcxxabi build from open source llvm has a different ABI from macOS system libcxx

What's happening in this specific case is that we have additional flavors of `operator new` and `operator delete` in the Apple system libc++, and those are not upstream. However, in the general case, it's a non-goal for upstream libc++ to be 100% ABI compatible with Apple's system libc++ -- or at least it's been a non-goal up to now.

To me, the fundamental problem seems to be that the linker is using `DYLD_LIBRARY_PATH` to pick up the right `libLTO.dylib`, which means that it will also pick up any "junk" in that directory. For example, if you `touch $PWD/build/repro-link-error/lib/libSystem.dylib`, I'd expect that everything's going to crash similarly because we'll use that empty file in place of the real `libSystem.dylib`. Possible "proper" fixes I can think about:
- The linker should use another mechanism to load `libLTO.dylib`. If `DYLD_LIBRARY_PATH` is the only suitable thing, would it make sense to then copy `libLTO.dylib` to a directory and `DYLD_LIBRARY_PATH` *that* path instead? Doesn't seem ideal, but I think that's the only way to ensure that we don't override arbitrary system dylibs by mistake.
- We should not collocate build products from the "runtimes" build with build products from the toolchain. They are conceptually at a different level, i.e. the toolchain is intended to be built and to run against the system libraries (libc++, libSystem, etc), whereas the runtimes (i.e. the just-built `libc++.dylib`, `libc++abi.dylib` and `libunwind.dylib`) are intended to be built and to run against each other. So maybe we should avoid putting both in the same directory to avoid these kinds of issues.
- Perhaps we could revisit the non-goal making Apple's system libc++ ABI compatible with upstream libc++. I don't think it's really worth pulling on that thread though, because I think that creates too many constraints for things we might want to do with the downstream libc++. This may require adding stuff to upstream libc++ that the project doesn't want to (nor should they be required to) maintain.
- Since 719b2ac42e42807c9282052718cbc91e0cac930c, we actually maintain some shims as an attempt to make the just-built `libc++.dylib` compatible with the system libc++. This is done for CI purposes exclusively, and that solution isn't perfect (for example we can only be ABI compatible with one version of the system library at a time, and the implementation of the shims is very naive). We could potentially pull on that thread further to accomplish ABI compatibility between the system libc++ and the upstream one, but again that would seem like only silencing the underlying issue (which is that the linker incorrectly picks up the non-system libc++).

Thoughts?

**Comment by cachemeifyoucan** [comment]
I don't what it takes to make basic compatibility with the system lidcxx on macOS. I hope we can do that because it seems we can't load libcxx via `DYLD_LIBRARY_PATH` as we might just accidentally crash system frameworks due to missing APIs. The only way to use open source libcxx is to select it during compile time.

**Comment by ldionne** [comment]
As I explained above, I don't think it's really feasible or desirable to *guarantee* ABI compatibility between Apple's internal system libc++ and LLVM's upstream libc++. They are differently-configured libraries and we want (need even) the ability to evolve them in slightly different ways depending on various factors. The `operator new(__type_descriptor_t)` work is a great example of that -- it doesn't really make sense for upstream libc++ to implement that vendor extension since we're pursuing Standardization with https://wg21.link/p2719, but that's definitely a feature that we (Apple) wanted to implement and deploy without needing to wait for upstream to be onboard. Every vendor is in a similar situation, and I think most vendors (e.g. Android) end up with an internal build that is also subtly incompatible with the vanilla upstream build.

In reality, we should have been using a different inline namespace from the beginning (e.g. `std::__apple::foo` instead of `std::__1::foo` like upstream), but that shipped has sailed so both libraries appear to be compatible on the surface.

I mostly mentioned that for completeness's sake, but I think it would be more productive to look into fixing this on the linker side.

**Comment by jysh1214** [comment]
Same problem.

**SOLUTION**:

My llvm config:
```
cmake -S llvm -B ./build -G Ninja \
  -D CMAKE_BUILD_TYPE=Release \
  -D LLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;mlir" \
  -D LLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind;openmp" \
  -D CMAKE_INSTALL_PREFIX=<my_path> \
  -D LLVM_PARALLEL_LINK_JOBS=8 && \
cmake --build ./build --target install
```

Then I build my repo using:
```
CXXFLAGS="-fuse-ld=lld" CFLAGS="-fuse-ld=lld" cmake --build ./build
```

All warning message are gone.

**Comment by carlocab** [comment]
> * We should not collocate build products from the "runtimes" build with build products from the toolchain. They are conceptually at a different level, i.e. the toolchain is intended to be built and to run against the system libraries (libc++, libSystem, etc), whereas the runtimes (i.e. the just-built `libc++.dylib`, `libc++abi.dylib` and `libunwind.dylib`) are intended to be built and to run against each other. So maybe we should avoid putting both in the same directory to avoid these kinds of issues.

At Homebrew, we're already doing something close to this: https://github.com/Homebrew/homebrew-core/blob/9a5d5c50aad6c436ed4cd46a6c070159a7ff5d63/Formula/l/llvm.rb#L180-L189

That is, instead of allowing `libc++[abi]` and `libunwind` to be installed into our LLVM package's `lib` directory, we install them into `lib/c++` and `lib/unwind` respectively. We've found need to do this because `ld64` will, for some reason, decide to link to LLVM's `libc++`/`libunwind` even if you only wanted to link to, say, `libLLVM` -- which seems like a separate (but related) issue to `ld64`'s use of `DYLD_LIBRARY_PATH`.

Perhaps a simpler fix for `ld64` is to use `DYLD_FALLBACK_LIBRARY_PATH` instead of `DYLD_LIBRARY_PATH`? I'm unsure if this will work the same way for the purposes of loading LLVM's `libLTO.dylib`, though.

**Comment by ynyyn** [comment]
I found another workaround, but it's pretty tricky. That is to add an Apple linker flag `-ld_classic`, which makes the Apple's `ld` use a legacy linker implementation—ld64 (ld-classic), instead of the "new" one, ld-prime, introduced in 2023.

Taking the minimal reproduction demo mentioned above, I found it goes work when adding `-Xlinker -ld_classic`:
```
echo "int main() {}" | $PWD/build/repro-link-error/bin/clang++ -v -xc++ - -Xlinker -ld_classic -o a.out
```

The legacy linker (ld64) does not seem to modify the `DYLD_LIBRARY_PATH` when `-lto_library` option is set, thus does not have the issue of loading incorrect dylibs.


However, this workaround is very tricky. Because ld-classic is deprecated. It throws a serious warning about being removed.

```
ld: warning: -ld_classic is deprecated and will be removed in a future release
```

But this workaround does work, and it somehow shows us where and when things got broken.

---

Here's some background information. Apple's linker `ld` was refactored in Xcode 15 (2023) and replaced with a brand new implementation called **ld-prime** (to distinguish when need). The original legacy linker `ld64` (also called **ld-classic** by Apple), is no longer in use.

So the Apple linker `ld` now uses ld-prime by default. To switch back to use the legacy ld64 linker, you can do it via `ld -ld_classic ...`; for example,

```shell
$ ld -v
@(#)PROGRAM:ld PROJECT:ld-1115.7.3
```

```shell
$ ld -ld_classic -v
ld: warning: -ld_classic is deprecated and will be removed in a future release
@(#)PROGRAM:ld-classic  PROJECT:ld64-954.16
```

You may notice that the versions of these two linkers are different. What happens behind the scenes is: when the `-ld_classic` option is present, `ld` delegates the invocation to its sibling standalone program `ld-classic`. And in my environment, the ld-prime is a product of `ld-1115.7.3`, while the ld-classic (ld64) implementation (forwarded internally via the `-ld_classic` option) comes from `ld64-954.16`.

Back to this issue. Based on the root cause summarized in the previous discussion, Apple's new linker ld-prime now modifies `DYLD_LIBRARY_PATH` when invoked with the `-lto_library` option to load `libLTO.dylib`, but this approach is somewhat "rough", causing unexpected dylibs to be incorrectly picked ("injected") during the load.

While the legacy linker ld64 doesn't behave this way. So intuitively, I believe this is a regression caused by the refactoring/update changes, and I think Apple's new linker should take such scenario into account and provide compatibility. As mentioned in previous discussion:

> The linker should use another mechanism to load `libLTO.dylib`.

But whether it can be achieved depends on whether the demands inside the Apple linker can be satisfied. Not sure if Apple is already tracking (or, willing to track or prioritize) this issue internally.

**Comment by cooperp** [comment]
>> The linker should use another mechanism to load libLTO.dylib.

>But whether it can be achieved depends on whether the demands inside the Apple linker can be satisfied. Not sure if Apple is already tracking (or, willing to track or prioritize) this issue internally.

Good news!  Yes we fixed it in Xcode 16.3 released earlier this year.  According to wikipedia that should be ld-1167.4.1 which matches the version i expect the fix shipped in.

**Comment by for-just-we** [comment]
I solved the problem by removing `-DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;` from the configuration arguments. So, only the system libc++.1.dylib exists.

**Comment by mizvekov** [comment]
I still see this problem even with `ld-1167.5`, so I am afraid it might not be fixed.
