### ISSUE TITLE
Missing intrinsic for clang-cl targeting arm64 windows

### ISSUE THREAD

**Issue by hendryklassen189** [llvm/llvm-project#121689]
Hello Developers!

This is an issue regarding compilation of c source code that contains ARM64 based intrinsic using clang-cl from llvm toolchain. Does intrinsic like '__ldar8' and '__ldar64' are supported by clang-cl tool? I am trying to compile the source code that involve these intrinsic on ARM64 based PC. 

My source :
![Image](https://github.com/user-attachments/assets/536cf9df-5b7a-41d6-9b69-521ab60b3295)
Error:
![Image](https://github.com/user-attachments/assets/d6f82587-9cb5-4e5a-96c4-e4b352a46d8e)
 

Thanks!!!

**Comment by DavidSpickett** [comment]
I think we are missing these. Full list from MSVC is here - https://learn.microsoft.com/en-us/cpp/intrinsics/arm64-intrinsics?view=msvc-170.

Judging by https://github.com/numpy/numpy/blob/main/numpy/_core/src/common/npy_atomic.h, we need:
* `__ldar8`
* `__ldar64` 
* `__ldar32`
* `__ldar16`, just to complete the set.

https://clang.llvm.org/docs/MSVCCompatibility.html#simd-and-instruction-set-intrinsic-behavior may be relevant if these instructions are part of an optional extension.

**Comment by DavidSpickett** [comment]
Related: https://github.com/llvm/llvm-project/issues/65405

**Comment by zafeerali943** [comment]
> Related: https://github.com/llvm/llvm-project/issues/65405

Do you have any plans to add support for the above intrinsic?

**Comment by DavidSpickett** [comment]
> I will have a go at implementing them.

Unfortunately I no longer have time to look at this.

(and if you are here because you searched for the error message, the solution that numpy implemented for the [issue](https://github.com/numpy/numpy/issues/28106) linked above may be interesting to you)

**Comment by zafeerali943** [comment]
@DavidSpickett this issue can be closed as the following intrinsics are related with CPP atomics and this issue has been fixed!
Thanks

**Comment by DavidSpickett** [comment]
As I understand it, a solution was found for numpy that avoids the need for these specific intrinsics. clang-cl is still missing them, so I will keep this issue open.
