### ISSUE TITLE
.clang-tidy not automatically find by clang-tidy 20.1.2

### ISSUE THREAD

**Issue by kenchung285** [llvm/llvm-project#136659]
I have a project that originally used clang-tidy 19.1.7, and we've recently upgraded to version 20.1.2. After upgrading, I've noticed a change in behavior regarding `.clang-tidy` file discovery.

In 19.1.7, `clang-tidy` was able to discover and apply our self-defined `.clang-tidy` files without explicitly passing the `-config-file` option. However, in 20.1.2, `clang-tidy` no longer discovers the `.clang-tidy` file at the project root unless we explicitly pass `-config-file`.

Worse, if we do pass the `-config-file` flag (pointing to the one in the project root), `clang-tidy` seems to ignore the `.clang-tidy` file under folder B, even when checking files located in that folder.

Here is the relevant directory structure:
```
project-root/
├── README.md
├── .clang-tidy           # Full rule config
├── folder A/
│   ├── some source files
│   └── ...
├── folder B/
│   └── .clang-tidy      # Contains "Checks: '-*'" to disable checks in this folder
└── folder C/
    ├── other source files
    └── ...
```

Expected behavior:
* Without `-config-file`, `clang-tidy` should find and respect both the project-root `.clang-tidy` and the one under `folder B`.

Actual behavior:
* Without `-config-file`, `.clang-tidy` is not found at all in 20.1.2.
* With `-config-file`, `.clang-tidy` in `folder B` is ignored.

**Comment by vbvictor** [comment]
Hi, this bug is possibly related to https://github.com/llvm/llvm-project/issues/134502 which was fixed a couple of weeks ago. Could you try trunk version of `clang-tidy` to confirm it? If you have debian-based os, you can get `clang-tidy-21` from here https://apt.llvm.org/ in "development branch".

**Comment by kenchung285** [comment]
Hi, do you mean using llvm 20.1.3? I've tried install 20.1.3 version but the clang-tidy still fails to find my `.clang-tidy` under project root

**Comment by vbvictor** [comment]
I mean current development branch, which currently has `clang-tidy-21`. In [apt.llvm.org](https://apt.llvm.org/) you can install nightly builds of `clang-tidy-21`.
I have a [small test repository](https://github.com/vbvictor/clang-tidy-multiconfg?tab=readme-ov-file) with multiple configs, and can not reproduce the bug with `clang-tidy-21`.
Could you make a reproducer that I can run locally? Or at least write contents of `.clang-tidy` config files with your run-commands so I can mimic your project structure and do your exact steps.

**Comment by carlosgalvezp** [comment]
The mentioned patch has not been ported to 20.1.3, since I believe it was fixed by my other commit.

@kenchung285 can you elaborate on what's the problem? What are you missing from the top-level file? Checks, HeaderFilter, check options, something else? 

Please provide a small reproducible example.

**Comment by kenchung285** [comment]
I have sent out a [pull request](https://github.com/vbvictor/clang-tidy-multiconfg/pull/1) for a small reproducible example base on @vbvictor 's test repository.  
PTAL, thanks!
cc @vbvictor @carlosgalvezp

**Comment by kenchung285** [comment]
@vbvictor I have another question is, in [apt.llvm.org](https://apt.llvm.org/) the installation instructions are using `apt` command.  
However, due to my team's restriction rules, we are not allowed to install packages from `apt`. I can only download the package and build with cmake on my machine.  
Is it possible to do so for nightly version, so that I could make sure if the nightly version works for me?

**Comment by carlosgalvezp** [comment]
@kenchung285 Thanks for the repro! I notice you are using `run-clang-tidy.py`. Can you try running the raw `clang-tidy` binary instead?

> Or just download the main branch and build it?

Yes, building from source is the easiest in your case.

**Comment by carlosgalvezp** [comment]
I re-created your repro in the attached tarball, then run my local build of clang-tidy 20.1.2:

```
/path/to/llvm-project/build/release/bin/clang-tidy -list-checks main.cpp --
```

And it prints the checks correctly. It also doesn't print any check if running on `lib1/foo.cpp`.

So I believe the clang-tidy binary is correct, the problem might be in `run-clang-tidy.py`.

[136659.tar.gz](https://github.com/user-attachments/files/19863162/136659.tar.gz)

**Comment by kenchung285** [comment]
@carlosgalvezp  I have try directly using `clang-tidy -list-checks` in my project and the checks are printed correctly. Thanks for your help!

But I'm still curious about why using the same `run-clang-tidy` displays different result when working with different version of clang-tidy?

**Comment by kenchung285** [comment]
@carlosgalvezp I found `run-clang-tidy` executes `clang-tidy` with `-list-checks` to displays the enabled checks:
https://github.com/llvm/llvm-project/blob/85b35a90770b6053f91d79ca685cdfa4bf6499a4/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py#L492-L517  

Therefore, I think if I can display correctly with `clang-tidy -list-checks`, it should work when using `run-clang-tidy.py`  
Could you try reproduce my case with the `run-clang-tidy.py`? So that we could know if I misuse the `run-clang-tidy.py` or it's a problem lies in `run-clang-tidy.py`  

Besides, the `run-clang-tidy.py` I'm using is the one I copy directly from the latest main branch of llvm-project.

**Comment by carlosgalvezp** [comment]
Ok, I can repro as follows:

```
clang-tidy -p path/to/build --list-checks --
```

It works if I specify the file:
```
clang-tidy -p path/to/build --list-checks path/to/foo.cpp --
```

**Comment by carlosgalvezp** [comment]
But this problem is happening only on the very first run of clang-tidy inside `run-clang-tidy`, which is intended just as a sanity check to see if one can run clang-tidy, and to display the active checks. It runs without any file at all. Later, it runs on the actual files (which are mandatory), and there I expect the checks to be active.

**Comment by carlosgalvezp** [comment]
Found the offending commit: 0249554ee1ac49e6f1d93fa78a55971fc706f635 
FYI @HerrCai0907 

This is happening on latest master.

Repro:

Take the tarball I posted above.
Run the following command from the directory containing the top-level `.clang-tidy` file:

```
/path/to/run-clang-tidy.py -clang-tidy-binary /path/to/build/bin/clang-tidy  -p /path/to/136659/build/
```

Expected: see the `performance` checks enabled.
Actual: `performance` checks don't show up.

**Comment by carlosgalvezp** [comment]
On the other hand, I'm not sure if `run-clang-tidy.py` relies on documented behavior. The docs say:
```
clang-tidy attempts to read configuration for each source file from a
  .clang-tidy file located in the closest parent directory of the source
  file.
```

So, clang-tidy requires a source file to be able to find the config. We do not document what happens if we call clang-tidy without a source file, which `run-clang-tidy.py` does.

**Comment by kenchung285** [comment]
> I found `run-clang-tidy` executes `clang-tidy` with `-list-checks` to displays the enabled checks

I'm curious about what options passed by `run-clang-tidy.py` to `clang-tidy`. By directly log the `invocation` variable just before subprocess run the command, I got
```
['/usr/local/bin/clang-tidy', '-p=build', '--allow-no-checks', '', '-list-checks', '-']
```

And after some manual test, I found that it is the empty string, `''`, in the command between `--allow-no-checks` and `-list-checks` makes the `clang-tidy`  of version `20.x` fail to find correct `.clang-tidy` inside the project. But version `19.x` works well in with this empty string.  

The empty string is appended at this line:
https://github.com/llvm/llvm-project/blob/0400b8e8fd2ff66c8faab1fa818dec8199d969ce/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py#L150

Does this empty string neccessary?

**Comment by kenchung285** [comment]
To reproduce the problem with empty string as file name with `clang-tidy` version `20.1.2`, 
```
/path/to/clang-tidy '' -list-checks -
```
Actual: performance checks don't show up.

However, 
```
/path/to/clang-tidy -list-checks - ''
```
Actual: see the performance checks enabled.

The differences between them is the position of the empty string.
If this differences is as expected, we can modify the `run-clang-tidy.py` to make the command run with correctly arranged argument and options.

**Comment by carlosgalvezp** [comment]
Hmm but what does your last command even mean? Arguments to the right of the dash are passed to Clang compiler. clang-tidy requires a file as input, so I believe the correct solution here is to create an empty temporary file, and pass that to clang-tidy (in `run-clang-tidy.py`).

**Comment by carlosgalvezp** [comment]
Or, I guess that's intended (but undocumented) behavior...
https://github.com/llvm/llvm-project/commit/65eccb463df7fe511c813ee6a1794c80d7489ff2

**Comment by HerrCai0907** [comment]
The reason is when we don't give file when list-checks, it will treat as dummy file in current folder.
But when we give a empty string, it will treat current folder as input file and find .clang-tidy in its parent folder.
Looks reasonable, I think what we can do it
1. Let run-clang-tidy.py pass a dummy file
2. Let clang-tidy --list-checks detect the path is file or folder and process them seperately.

**Comment by carlosgalvezp** [comment]
As per https://github.com/llvm/llvm-project/commit/65eccb463df7fe511c813ee6a1794c80d7489ff2, if we want to simply "list-checks", we should not pass any file at all.

Therefore, run-clang-tidy.py should pass None instead of an empty string when calling -list-checks. I have tested this and it works, will put up a patch!

**Comment by carlosgalvezp** [comment]
@kenchung285 Can you test the above PR? It's just a change in `run_clang_tidy.py`

**Comment by kenchung285** [comment]
Sorry, I can't access my team's system on weekend. I'll test the PR next Monday. Does this cause any inconvenience?

**Comment by carlosgalvezp** [comment]
No problem! As long as we make it in time for the next release :)

**Comment by carlosgalvezp** [comment]
@kenchung285 Did you have a chance to test this?

**Comment by kenchung285** [comment]
Hi @carlosgalvezp, I've just test your PR with my system. It works well!  
Thanks for your help!

**Comment by carlosgalvezp** [comment]
Great, thank you for testing it! I'll try to make it into 20.1.3, otherwise 20.1.4
