### ISSUE TITLE
[clangd] Crash when `char[]` is initialized with both `#embed` and literal values

### ISSUE THREAD

**Issue by 398utubzyt** [llvm/llvm-project#138439]
```c
char message[] = {
#embed "message.txt"
, 0
};
```

The code above will crash when hovering over `message`. It functions as normal without the `, 0` bit.

```
LLVM ERROR: Not implemented
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Signalled during AST worker action: Hover
  Filename: main.cpp
  Directory: d:\source\cpp\hover_crash\src\main
  Command Line: D:\Tools\Clang\20.1.0\bin\clang -resource-dir=D:\Tools\Clang\20.1.0\lib\clang\20 -- d:\source\cpp\hover_crash\src\main\main.cpp
  Version: 84
```
The logs don't seem to give a backtrace.

**Comment by cor3ntin** [comment]
@398utubzyt hovering?  Is that a clangd bug?

**Comment by tbaederr** [comment]
This is probably fixed by https://github.com/llvm/llvm-project/pull/135957

**Comment by 398utubzyt** [comment]
> [@398utubzyt](https://github.com/398utubzyt) hovering? Is that a clangd bug?

Indeed it's a clangd bug. It's in the title.

> This is probably fixed by [#135957](https://github.com/llvm/llvm-project/pull/135957)

The crash still occurs on 20.1.4 (latest official release as of writing), and it seems like [#135957](https://github.com/llvm/llvm-project/pull/135957) was merged prior to its release? I can confirm that `#embed` on its own behaves correctly, but the crash is caused by the inclusion of the following extra data: `, 0`.

**Comment by tbaederr** [comment]
@Fznamznon Did you ever backport that fix to the 20 branch?

**Comment by Fznamznon** [comment]
> [@Fznamznon](https://github.com/Fznamznon) Did you ever backport that fix to the 20 branch?

No, I did not.

**Comment by tbaederr** [comment]
It affects people so I think backporting it makes sense

**Comment by Fznamznon** [comment]
Sorry for the delay, one of the tests is crashing when the patch is applied to clang 20.x for a reason that I don't know. Is that still worth pursuing?

**Comment by cor3ntin** [comment]
@Fznamznon Probably not https://discourse.llvm.org/t/llvm-20-x-release-schedule-update/86688 @AaronBallman
