### ISSUE TITLE
[AVR] llvm-objdump should automatically select the instruction set

### ISSUE THREAD

**Issue by benshi001** [llvm/llvm-project#146451]
Given a simple test program:
```c++
int adiw(int a) {
	return a + 51;
}
```

Build it with `clang a.c --target=avr -mmcu=avr2 -c -O3`, and then disassemble it with `llvm-objdump -d a.o`, we see
```asm
a.o:	file format elf32-avr

Disassembly of section .text:

00000000 <adiw>:
       0: c3 96 08 95  	<unknown>
```

We must specify `--mcpu=avr2` to `llvm-objdump` explicitly to make `adiw` correctly  decoded.
```asm
a.o:	file format elf32-avr

Disassembly of section .text:

00000000 <adiw>:
       0: c3 96        	adiw	r24, 0x33
       2: 08 95        	ret
```

However the generated object file does contain the `avr2` family information.
```bash
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           Atmel AVR 8-bit microcontroller
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          284 (bytes into file)
  Flags:                             0x82, EF_AVR_ARCH_AVR2, relaxable
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         5
  Section header string table index: 1
```

So the `llvm-objdump` should automatically select the avr family according to ELF header, other than rely on user's explicit specification.

**Comment by MaskRay** [comment]
I have implemented the following for AArch64 and PowerPC

* AArch64: https://reviews.llvm.org/D128030 --mattr=+all
* powerpc64: https://reviews.llvm.org/D127824 --mcpu=future

**Comment by benshi001** [comment]
> I have implemented the following for AArch64 and PowerPC
> 
> * AArch64: https://reviews.llvm.org/D128030 --mattr=+all
> * powerpc64: https://reviews.llvm.org/D127824 --mcpu=future

Thanks. I will study your way. What I am hoping are 
1. decode supported instructions for a specific avr family
2. still show `<unknown>` for unsupported instructions

It seems default to `--mattr=+all` can not meet my expectation.
