### ISSUE TITLE
OrcJitTests unittest ReOptimizeLayerTest.BasicReOptimization fails on windows

### ISSUE THREAD

**Issue by OCHyams** [llvm/llvm-project#158270]
`ReOptimizeLayerTest.BasicReOptimization` fails locally for me and on an internal bot (but doesn't seem to be failing on any upstream bots):

```
>ninja OrcJITTests &&  unittests\ExecutionEngine\Orc\OrcJITTests.exe
...
[----------] 1 test from ReOptimizeLayerTest
[ RUN      ] ReOptimizeLayerTest.BasicReOptimization
JIT session error: In graph <main>-jitted-objectbuffer, section .pdata: relocation target 0x22d3eea2000 (.text) is out of range of Pointer32 fixup at address 0x22d3eea2000 (<anonymous block> @ 0x22d3eea0014 + 0x0)
unknown file: error: SEH exception with code 0x3221225477 thrown in the test body.
Stack trace:


[  FAILED  ] ReOptimizeLayerTest.BasicReOptimization (19 ms)
[----------] 1 test from ReOptimizeLayerTest (19 ms total)
```

Weirdly, running the unittest with `--gtest_filter=ReOptimizeLayerTest.BasicReOptimization` it passes.

---

cl.exe version:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34435 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

I also tried building with clang but saw the same failure:
```
clang version 22.0.0git (https://github.com/llvm/llvm-project 4d24407e7d0ae66a8fef29f2100706d85706ae10)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\gbhyamso\dev\llvm-project\build\bin
Build config: +assertions
```

**Comment by OCHyams** [comment]
@lhames I think this was introduced by https://github.com/llvm/llvm-project/commit/f93df5ebd992686f858606a5181ae99be0d2b354, do you have any idea what's happening?

**Comment by lhames** [comment]
Should be fixed by https://github.com/llvm/llvm-project/pull/163495.

**Comment by OCHyams** [comment]
Thanks for taking a look at it! Unfortunately with the patch applied it's still failing for me. Have you been able to reproduce the issue? Please let me know if there's anything I can do to help diagnose it.
