### ISSUE TITLE
[concepts] out-of-line definition of constrained members is not accepted

### ISSUE THREAD

**Issue by Ivan171** [llvm/llvm-project#49620]
|  |  |
| --- | --- |
| Bugzilla Link | [50276](https://llvm.org/bz50276) |
| Version | trunk |
| OS | Windows NT |
| CC | @Ivan171,@zygoloid |

## Extended Description 
```
$ cat utf.cpp
#include <concepts>

template <typename>
struct utf_t;

template <typename T>
    requires (std::is_same_v<T, char32_t>) ||
             (std::is_same_v<T, wchar_t> && sizeof(wchar_t) == sizeof(char32_t))
struct utf_t<T> {
  utf_t() {
  }

  template <typename Input>
  static auto length(Input begin, Input const end) -> unsigned;
};

template <typename T>
    requires (std::is_same_v<T, char32_t>) ||
             (std::is_same_v<T, wchar_t> && sizeof(wchar_t) == sizeof(char32_t))
template <typename Input>
inline auto utf_t<T>::length(Input begin, Input const end) -> unsigned {
  return 0;
}

$ clang++ -std=c++20 utf.cpp
utf.cpp:21:23: error: out-of-line definition of 'length' from class 'utf_t<type-parameter-0-0>' without definition
inline auto utf_t<T>::length(Input begin, Input const end) -> unsigned {
            ~~~~~~~~~~^
1 error generated.
```

No matter how you constrain it, it doesn't work: https://godbolt.org/z/qqaM89nTx

GCC compiles it without any error: https://godbolt.org/z/PM3seoYvW

**Comment by palchak-google** [comment]
Here's a slightly simpler example that also demonstrates how easy it is to hit this defect:
https://godbolt.org/z/55T5vvK3f

**Comment by jwakely** [comment]
Another example from #58124, this one reduced from libstdc++ code:

```
template<class T> concept C1 = true;
template<class T> concept C2 = C1<T> && true;

template<C1> struct X { };
template<C2 T> struct X<T> { struct Y; };

template<C2 T> struct X<T>::Y { }; // (1)
```

**Comment by royjacobson** [comment]
We cache template specializations inside `ASTContext::getCanonicalTemplateSpecializationType`. I think it is not smart enough to distinguish between the partial constrained specialization and the primary template. When I manually (in gdb) cause the primary template to be hashed into a different value, clang seems to compile the rest of the code.

However, this function only receives a vector of `TemplateArgument`s. And I have no idea how to correctly propagate this information to retrieve the correct specialization, so I'm kinda giving up for now :/

**Comment by royjacobson** [comment]
So, I'm pretty sure we have to store a `TypeConstraint` inside of `TemplateTypeParmType`, but it's a pretty big change that I don't have the time to commit to :/

**Comment by alexander-shaposhnikov** [comment]
I've been looking into this for quite some time, I hope to have an update ~soon

**Comment by usx95** [comment]
This looks fixed at trunk. Thank you very much @alexander-shaposhnikov

**Comment by Romain-Geissler-1A** [comment]
Great ! Is this something that is worth backporting in the freshly released Clang 16 ?

**Comment by Romain-Geissler-1A** [comment]
(note: the commit says it partially fixes this issue, not fully fixes it, yet I have no idea what is still broken ;) )

**Comment by usx95** [comment]
There are still outstanding out-of-line definition bugs. (Hotlist: https://github.com/orgs/llvm/projects/14/views/1?filterQuery=is%3Aopen+label%3Aconcepts+priority%3AP0+out-of-line)

But the cases mentioned on this one and in its dups are all fixed.

**Comment by jodvova** [comment]
Would be good if this is back-ported to a freshly released Clang 16. We're cross-compiling with gcc and clang and unfortunately can't upgrade gcc right now.

**Comment by mikeynap** [comment]
Are there any plans to include this in 16.0.3?

**Comment by jodvova** [comment]
Has this been included in recently released 16.0.4 ?

**Comment by alexander-shaposhnikov** [comment]
(closing the issue since it's fixed)

**Comment by xaxazak** [comment]
Bug still exists.

```
namespace moo
	{
		template <typename T>
		constexpr bool baa = true;
		
		template <typename T> requires baa<T>
		void caw();
	}
// moo::


template <typename T> requires moo::baa<T>
void moo::caw() {}
```
[compiler-explorer](https://godbolt.org/z/vGoavxf7M)

error: out-of-line definition of 'caw' does not match any declaration in namespace 'moo'

**Comment by shafik** [comment]
> Bug still exists.

This is a bit confusing to say, the original code in this issue is now accepted but there are related issues that do not. So no need to reopen this bug.
