### ISSUE TITLE
lldb with -o run, ctrl-c does not work anymore

### ISSUE THREAD

**Issue by paddor** [llvm/llvm-project#53673]
I'm using `lldb version 13.0.1` and I read that this is an old bug (from LLDB 10), so I'm assuming this is a regression. If started with `lldb -o run ...`, interrupts from ctrl-c are ignored.

**Comment by DavidSpickett** [comment]
Confirmed on main on AArch64 Ubuntu.

```
$ cat /tmp/test.c
int main() {
  while (1) {}
  return 0;
}
$ gcc /tmp/test.c -o /tmp/test.o -g
$ ./bin/lldb /tmp/test.o -o run
(lldb) target create "/tmp/test.o"
Current executable set to '/tmp/test.o' (aarch64).
(lldb) run
^C^C^C
```

I will see if I can find the regression point, if it did ever work.

**Comment by paddor** [comment]
It also happens on `lldb version 12.0.0`

**Comment by DavidSpickett** [comment]
Present as far back as 7.0.1 so it's a general issue we've always had. Guess - the run is issued before we've bound all the right hooks to pass on the ctrl-c.

I'll dig around and see how the `-o` is handled.

**Comment by DavidSpickett** [comment]
This is something to do with the IO Hanlder(s?) are or are not run. With some prinfts sprinkled around:
```
$ ./bin/lldb /tmp/test.o
CommandInterpreter::RunCommandInterpreter running IO Handlers!
Debugger::RunIOHandlers Running IO Handler!
(lldb) target create "/tmp/test.o"
Current executable set to '/tmp/test.o' (aarch64).
CommandInterpreter::RunCommandInterpreter running IO Handlers!
Debugger::RunIOHandlers Running IO Handler!
(lldb) run
Process 817810 launched: '/tmp/test.o' (aarch64)
Debugger::RunIOHandlers Running IO Handler!
Run!
Sending interrupt!
Was active!
Can read pipe: 1 Can write pipe: 1
Did write? 1
read char from pipe, got i
Process 817810 stopped
* thread #1, name = 'test.o', stop reason = signal SIGSTOP
    frame #0: 0x0000aaaaaaaaa71c test.o`main at test.c:2:9
   1    int main() {
-> 2      while (1) {}
   3      return 0;
   4    }
read char from pipe, got q
Debugger::RunIOHandlers Running IO Handler!
(lldb) ^D
```
Pressing ctrl-c puts 'i' into a pipe that should be picked up by the IO Handler, which is run after we do `run`.

Now the failing case:
```
$ ./bin/lldb /tmp/test.o -o run
CommandInterpreter::RunCommandInterpreter running IO Handlers!
Debugger::RunIOHandlers Running IO Handler!
(lldb) target create "/tmp/test.o"
Current executable set to '/tmp/test.o' (aarch64).
(lldb) run
^CSending interrupt!
Was active!
Can read pipe: 1 Can write pipe: 1
Did write? 1
```
The 'i' is written to the pipe but no one is listening on the other end. Also interesting that we don't see "Process <num> launched: '/tmp/test.o' (aarch64)" in this case. Which is probably my clue for the root cause.

**Comment by EugeneZelenko** [comment]
@paddor: Is issue fixed in newer versions?

**Comment by paddor** [comment]
> @paddor: Is issue fixed in newer versions?

I don't know. I didn't check.

**Comment by DavidSpickett** [comment]
Still present on `main` as of 4c853be6673fd95b4b900a6c0e1804bf33a0629c.

**Comment by k4lizen** [comment]
still present on lldb version 22.1.8
