### ISSUE TITLE
Fix compatibility issue between clang and libstdc++ <atomic> with 64-bit atomic struct

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#54963]
If the 64-bit atomic type is a struct, and its natural alignment is less than 8, clang will generate a call to libatomic.  This call shouldn't be necessary: the "atomic" type has increased alignment, so the variable will be naturally aligned.  Originally reported at #54790

Testcase:

```
#include <atomic>
struct X{char x[8];};
std::atomic<uint64_t> x;
std::atomic<X> x2;
void f() { x = {10}; }
void f2() { x2 = {10}; }
```

Looking at the internal implementation of libstdc++, this boils down to something like:

```
#include <memory>
struct X{char x[8];};
struct alignas(8) Y { X x; };
void f(Y *y, X* val) {
  __atomic_store(std::addressof(y->x), val, 0);
}
```

Original proposed fix at https://reviews.llvm.org/D123642, but @jyknight didn't like that fix, so I'm looking at the alternative of special-casing calls to std::addressof.  b27430f9f should make this easy.

**Comment by efriedma-quic** [comment]
Fixed by https://reviews.llvm.org/D123950 .

(Not planning to cherry-pick this to LLVM 14 branch; it's not a regression, and it depends on b27430f9, which is not suitable to cherry-pick.)

**Comment by satmandu** [comment]
Debian continues to work around this i386 build issue that still exists in LLVM 23.1 by adding `-atomic` to 32-bit x86 builds with https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/raw/23/debian/patches/clangd-atomic-cmake.patch?ref_type=heads&inline=false .

**Comment by efriedma-quic** [comment]
That might be https://github.com/llvm/llvm-project/issues/177701... but please open a new bug describing the current symptoms, and preprocessed source for whatever file is referencing "atomic".  Commenting on old closed bugs isn't useful.
