### ISSUE TITLE
BOLT fails to instrument clang on AArch64 host

### ISSUE THREAD

**Issue by nathanchance** [llvm/llvm-project#55005]
I am not sure if this issue is a bug or more of a "not expected to work yet" issue, as I recall seeing somewhere that BOLT instrumentation was only supported for x86_64 but I did not get an immediate error and I see `AArch64` throughout `bolt/` so I figured I would report it and let someone close it if it is a known issue.

On an AArch64 host (the one I tested on uses an Ampere Altra Q80-30), `llvm-bolt` fails to instrument `clang`. My reproduction steps at cfb8169059c807ed5fbfb66b3ed558b7b6eb2833:

```
$ cmake \
-B build/stage1 \
-G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_COMPILER=/usr/bin/clang \
-DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
-DCMAKE_EXE_LINKER_FLAGS=-Wl,-q \
-DLLVM_ENABLE_TERMINFO=OFF \
-DLLVM_ENABLE_PROJECTS="clang;bolt" \
-DLLVM_TARGETS_TO_BUILD=host \
-DLLVM_USE_LINKER=/usr/bin/ld.lld \
-S llvm

$ ninja -C build/stage1 clang llvm-bolt

$ build/stage1/bin/llvm-bolt \
--instrument \
--instrumentation-file=$PWD/build/clang.fdata \
-o build/stage1/bin/clang.inst \
build/stage1/bin/clang-15
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: cfb8169059c807ed5fbfb66b3ed558b7b6eb2833
BOLT-INFO: first alloc address is 0x200000
BOLT-INFO: creating new program header table at address 0x5000000, offset 0x4e00000
BOLT-INFO: enabling relocation mode
BOLT-INFO: forcing -jump-tables=move for instrumentation
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
=======================================
BOLT is unable to proceed because it couldn't properly understand this function.
If you are running the most recent version of BOLT, you may want to report this and paste this dump.
Please check that there is no sensitive contents being shared in this dump.

Offending function: __do_global_dtors_aux/1

Function contents (
  0000: 3F2303D5 FD7BBEA9 FD030091 F30B00F9  |?#...{..........|
  0010: B3CF0190 60824739 80000035 DDFFFF97  |....`.G9...5....|
  0020: 20008052 60820739 F30B40F9 FD7BC2A8  | ..R`..9..@..{..|
  0030: BF2303D5 C0035FD6 1F2003D5 1F2003D5  |.#...._.. ... ..|
)

Binary Function "__do_global_dtors_aux/1"  {
  Number      : 7
  State       : disassembled
  Address     : 0x13cc550
  Size        : 0x38
  MaxSize     : 0x40
  Offset      : 0x11bc550
  Section     : .text
  Orc Section : .local.text.__do_global_dtors_aux/1
  LSDA        : 0x0
  IsSimple    : 1
  IsMultiEntry: 0
  IsSplit     : 0
  BB Count    : 0
}
.LBB06:
    00000000:   hint    #25
    00000004:   stp     x29, x30, [sp, #-0x20]!
    00000008:   mov     x29, sp
    0000000c:   str     x19, [sp, #0x10]
    00000010:   adrp    x19, "completed.0/1"
    00000014:   ldrb    w0, [x19, :lo12:"completed.0/1"]
    00000018:   cbnz    w0, .Ltmp4 # Offset: 24
    0000001c:   bl      "deregister_tm_clones/1" # Offset: 28
    00000020:   mov     w0, #0x1
    00000024:   strb    w0, [x19, :lo12:"completed.0/1"]
.Ltmp4:
    00000028:   ldr     x19, [sp, #0x10]
    0000002c:   ldp     x29, x30, [sp], #0x20
    00000030:   hint    #29
    00000034:   ret     x30 # Offset: 52
DWARF CFI Instructions:
    <empty>
End of Function "__do_global_dtors_aux/1"

ERROR: unable to fill CFI.
=======================================
```

**Comment by aaupov** [comment]
Hi @nathanchance,

Yes, instrumentation is not supported on AArch64 yet. Cc @yota9

**Comment by EugeneZelenko** [comment]
It'll be great if BOLT will complain about unsupported features in more comprehensive way.

**Comment by yota9** [comment]
> Hi @nathanchance,
> 
> Yes, instrumentation is not supported on AArch64 yet. Cc @yota9

We hope it will be available one day, currently it is still under construction by hq :(

**Comment by hpesoj** [comment]
I'm getting a similar error running `perf2bolt` on an AArch64 binary. Is this also not supported?

**Comment by sebpop** [comment]
Adding verbosity `-v 1` to perf2bolt shows a warning:
```
BOLT-WARNING: DW_CFA_GNU_* and DW_CFA_*_user unimplemented
```
gdb points out the missing dwarf info is: `DW_CFA_GNU_window_save`

A patch to handle this opcode makes perf2bolt succeed:
```
commit a937f7d6bf7f542d60dd70577bfad93aebcbed5d (HEAD -> main)
Author: Sebastian Pop <spop@amazon.com>
Date:   Wed Jan 25 18:40:48 2023 +0000

    [AArch64] fix bug #55005
    
    GCC on AArch64 uses DW_CFA_GNU_window_save for return address signing.
    
    In architecture revisions prior to ARMv8.3-A the pointer authentication
    HINT instructions operate as NOPs.

diff --git a/bolt/lib/Core/Exceptions.cpp b/bolt/lib/Core/Exceptions.cpp
index f8eabcf48f83..aaa8497001ff 100644
--- a/bolt/lib/Core/Exceptions.cpp
+++ b/bolt/lib/Core/Exceptions.cpp
@@ -626,11 +626,13 @@ bool CFIReaderWriter::fillCFIInfoFor(BinaryFunction &Function) const {
         errs() << "BOLT-WARNING: DW_CFA_MIPS_advance_loc unimplemented\n";
       return false;
     case DW_CFA_GNU_window_save:
+      Function.addCFIInstruction(
+          Offset, MCCFIInstruction::createWindowSave(nullptr));
+      break;
     case DW_CFA_lo_user:
     case DW_CFA_hi_user:
       if (opts::Verbosity >= 1) {
-        errs() << "BOLT-WARNING: DW_CFA_GNU_* and DW_CFA_*_user "
-                  "unimplemented\n";
+        errs() << "BOLT-WARNING: DW_CFA_*_user unimplemented\n";
       }
       return false;
     default:

```

`DW_CFA_GNU_window_save` has been added to gcc/arm64 in this proposal:
https://gcc.gnu.org/legacy-ml/gcc-patches/2016-11/msg03010.html
>   As one new DWARF call frame instruction is needed for AArch64, I want to reuse
  DW_CFA_GNU_window_save to save the space.  It is in vendor extension space and
  used for Sparc only, I think it make sense to reuse it for AArch64. On
  AArch64, DW_CFA_GNU_window_save toggle return address sign status which kept
  in a new boolean type column in DWARF table,  so DW_CFA_GNU_window_save takes
  no argument on AArch64, the same as on Sparc, this makes no difference to those
  existed encoding, length calculation code.

and in this patch for the return address signing code generation:
https://gcc.gnu.org/legacy-ml/gcc-patches/2017-01/msg00376.html

**Comment by aaupov** [comment]
@sebpop - thanks for fixing this. You can commandeer the diff I created on Phabricator: https://reviews.llvm.org/D142572

**Comment by sebpop** [comment]
Fixed.

**Comment by bincheng-github** [comment]
Hi Sebpop, Thanks for fixing the perf2bolt issue, however, the issue was to track the instrument support on AArch64, which is a different problem (not solved yet)?

**Comment by sebpop** [comment]
Thanks for pointing out that the bug has another dimension that I have not tested.
I'm reopening the bug.

**Comment by yota9** [comment]
The instrumentation is now available for aarch64, so closing the issue
