### ISSUE TITLE
clang crashes on valid code at -Os and above on x86_64-linux-gnu: Stack overflow due to getSCEVAtScope/computeSCEVAtScope recursion

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#55511]
It appears to be a recent regression.

```console
% clangtk -v
clang version 15.0.0 (https://github.com/llvm/llvm-project.git 6e23cd2bf073ab5eb5a103b935af54046d007c52)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64
[524] % 
[524] % clangtk -Os small.c
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /local/suz-local/software/local/clang-trunk/bin/clang-15 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name small.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/local/suz-local/software/emitesting/bugs/20220516-clangtk-m64-O3-build-161829/delta -resource-dir /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0 -I /usr/local/include/csmith -I /local/suz-local/software/local/include -internal-isystem /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Os -fdebug-compilation-dir=/local/suz-local/software/emitesting/bugs/20220516-clangtk-m64-O3-build-161829/delta -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/small-3a128b.o -x c small.c
1.	<eof> parser at end of file
2.	Optimizer
  #0 0x000055a1b9f28adf PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
  #1 0x000055a1b9f2654c SignalHandler(int) Signals.cpp:0:0
  #2 0x00007fa786e8a980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
  #3 0x000055a1b8fb063b computeKnownBitsFromAssume(llvm::Value const*, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #4 0x000055a1b8facdad computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #5 0x000055a1b8fad41b computeKnownBits(llvm::Value const*, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #6 0x000055a1b8faac1b computeKnownBitsFromOperator(llvm::Operator const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #7 0x000055a1b8fad215 computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #8 0x000055a1b8faa2aa computeKnownBitsFromOperator(llvm::Operator const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #9 0x000055a1b8fad215 computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
 #10 0x000055a1b8faa45a computeKnownBitsFromOperator(llvm::Operator const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
 #11 0x000055a1b8fad215 computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
 #12 0x000055a1b8fad41b computeKnownBits(llvm::Value const*, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
 #13 0x000055a1b8fb05d8 computeKnownBits(llvm::Value const*, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
 #14 0x000055a1b8fb2bdb llvm::computeKnownBits(llvm::Value const*, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::Instruction const*, llvm::DominatorTree const*, llvm::OptimizationRemarkEmitter*, bool) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2ae9bdb)
 #15 0x000055a1b8f1e842 llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a55842)
 #16 0x000055a1b8f1e5d6 llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a555d6)
 #17 0x000055a1b8f1e97c llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a5597c)
 #18 0x000055a1b8f1e5d6 llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a555d6)
 #19 0x000055a1b8f1ea4c llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a55a4c)
 #20 0x000055a1b8f1e5d6 llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a555d6)
 #21 0x000055a1b8f2f66f llvm::ScalarEvolution::getRangeRef(llvm::SCEV const*, llvm::ScalarEvolution::RangeSignHint) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a6666f)
 #22 0x000055a1b8f316c5 llvm::ScalarEvolution::isKnownNonNegative(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a686c5)
 #23 0x000055a1b8f52077 llvm::ScalarEvolution::getGEPExpr(llvm::GEPOperator*, llvm::SmallVectorImpl<llvm::SCEV const*> const&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a89077)
 #24 0x000055a1b8f5222d llvm::ScalarEvolution::createNodeForGEP(llvm::GEPOperator*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a8922d)
 #25 0x000055a1b8f385db llvm::ScalarEvolution::createSCEV(llvm::Value*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a6f5db)
 #26 0x000055a1b8f39c4f llvm::ScalarEvolution::getSCEV(llvm::Value*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a70c4f)
 #27 0x000055a1b8f4d252 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a84252)
 #28 0x000055a1b8f4dc45 llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a84c45)
 #29 0x000055a1b8f4da84 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a84a84)
 #30 0x000055a1b8f4dc45 llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2a84c45)

...

clang-15: error: unable to execute command: Segmentation fault
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 15.0.0 (https://github.com/llvm/llvm-project.git 6e23cd2bf073ab5eb5a103b935af54046d007c52)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
clang-15: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/small-ba1158.c
clang-15: note: diagnostic msg: /tmp/small-ba1158.sh
clang-15: note: diagnostic msg: 

********************
% 
% cat small.c
int a[6], b, c, d, e, f, g, i;
int main() {
  for (c = 0; c > -2; c--)
    ;
  f = ~(c - 1);
  if (f < 2)
    for (; d; d--)
      for (i = 0; i < 10; i++)
        for (g = 0; g < 6; g++)
          for (e = 0; e < 3; e++)
            for (c = 0; c < 6; c++) {
              b = a[(b ^ 5) & 15];
              b = a[(b ^ 5) & 15];
              b = a[(b ^ 5) & 15];
            }
  return 0;
}
```

Compiler Explorer: https://godbolt.org/z/vnos8Toqv 

@fhahn

**Comment by fhahn** [comment]
This looks like the same issue as https://github.com/llvm/llvm-project/issues/44546. SCEV overflows the stack due to recursively constructing expressions.

But I cannot confirm this unfortunately, as it doesn't reproduce on my system, likely due to different stack size limits.

**Comment by fhahn** [comment]
Should be fixed by https://github.com/llvm/llvm-project/commit/675080a4533b91b3b62e51d3659629bc020fb940. It would be great if you could verify it fixes the issue on your side.

**Comment by zhendongsu** [comment]
Hi Florian, it still crashes for me with the latest build on Ubuntu 18.04:
```
[510] % clangtk -v
clang version 15.0.0 (https://github.com/llvm/llvm-project.git 9d2e830737bcf8035cf263e4b4cb279b7b07cf24)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 11.0
[511] % 
[511] % clangtk -Os pr55511.c 
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /local/suz-local/software/local/clang-trunk/bin/clang-15 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name pr55511.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/home/suz -resource-dir /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0 -I /usr/local/include/csmith -I /local/suz-local/software/local/include -internal-isystem /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Os -fdebug-compilation-dir=/home/suz -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/pr55511-1c4c41.o -x c pr55511.c
1.	<eof> parser at end of file
2.	Optimizer
  #0 0x000055b60d0772af PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
  #1 0x000055b60d074cdc SignalHandler(int) Signals.cpp:0:0
  #2 0x00007f1c0ba71980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
  #3 0x000055b60c0efd8b computeKnownBitsFromAssume(llvm::Value const*, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #4 0x000055b60c0ec5dd computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #5 0x000055b60c0ea3da computeKnownBitsFromOperator(llvm::Operator const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #6 0x000055b60c0eca18 computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #7 0x000055b60c0e9fc2 computeKnownBitsFromOperator(llvm::Operator const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #8 0x000055b60c0eca18 computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #9 0x000055b60c0ecc0b computeKnownBits(llvm::Value const*, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
 #10 0x000055b60c0efd28 computeKnownBits(llvm::Value const*, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
 #11 0x000055b60c0f214b llvm::computeKnownBits(llvm::Value const*, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::Instruction const*, llvm::DominatorTree const*, llvm::OptimizationRemarkEmitter*, bool) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c1614b)
 #12 0x000055b60c05a942 llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b7e942)
 #13 0x000055b60c05a6d6 llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b7e6d6)
 #14 0x000055b60c05aa7c llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b7ea7c)
 #15 0x000055b60c05a6d6 llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b7e6d6)
 #16 0x000055b60c05ab4c llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b7eb4c)
 #17 0x000055b60c05a6d6 llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b7e6d6)
 #18 0x000055b60c06b337 llvm::ScalarEvolution::getRangeRef(llvm::SCEV const*, llvm::ScalarEvolution::RangeSignHint) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b8f337)
 #19 0x000055b60c06d325 llvm::ScalarEvolution::isKnownNonNegative(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b91325)
 #20 0x000055b60c08dc67 llvm::ScalarEvolution::getGEPExpr(llvm::GEPOperator*, llvm::SmallVectorImpl<llvm::SCEV const*> const&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bb1c67)
 #21 0x000055b60c08de1d llvm::ScalarEvolution::createNodeForGEP(llvm::GEPOperator*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bb1e1d)
 #22 0x000055b60c0741e3 llvm::ScalarEvolution::createSCEV(llvm::Value*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b981e3)
 #23 0x000055b60c075870 llvm::ScalarEvolution::createSCEVIter(llvm::Value*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2b99870)
 #24 0x000055b60c088715 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bac715)
 #25 0x000055b60c089185 llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bad185)
 #26 0x000055b60c088be4 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bacbe4)
 #27 0x000055b60c089185 llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bad185)
 #28 0x000055b60c088be4 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bacbe4)
 #29 0x000055b60c089185 llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bad185)
 #30 0x000055b60c088727 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bac727)
 #31 0x000055b60c089185 llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2bad185)
...
clang-15: error: unable to execute command: Segmentation fault
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 15.0.0 (https://github.com/llvm/llvm-project.git 9d2e830737bcf8035cf263e4b4cb279b7b07cf24)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
clang-15: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/pr55511-a287b2.c
clang-15: note: diagnostic msg: /tmp/pr55511-a287b2.sh
clang-15: note: diagnostic msg: 

********************
[512] % 
[512] % cat pr55511.c 
int a[6], b, c, d, e, f, g, i;
int main() {
  for (c = 0; c > -2; c--)
    ;
  f = ~(c - 1);
  if (f < 2)
    for (; d; d--)
      for (i = 0; i < 10; i++)
        for (g = 0; g < 6; g++)
          for (e = 0; e < 3; e++)
            for (c = 0; c < 6; c++) {
              b = a[(b ^ 5) & 15];
              b = a[(b ^ 5) & 15];
              b = a[(b ^ 5) & 15];
            }
  return 0;
}
```
@fhahn

**Comment by fhahn** [comment]
@zhendongsu thanks, looking at the stack trace on godbolt it looks like the mutual recursion between `getSCEVAtScope` and `computeSCEVAtScope` is the issue here .

Would it be possible to extract an IR reproducer for `opt` alone, using `-mllvm -print-on-crash -mllvm -print-module-scope`? When adding those flags on godbolt, the crash goes away for some reason.

**Comment by zhendongsu** [comment]
@fhahn here it is:
[pr55511.txt](https://github.com/llvm/llvm-project/files/9011912/pr55511.txt)

**Comment by fhahn** [comment]
Thanks! I am afraid someone else will need to investigate this one, as I am not able to reproduce this locally (on macOS).

**Comment by zhendongsu** [comment]
Another similar repro in case it may be of some help:
```
[506] % clangtk -v
clang version 15.0.0 (https://github.com/llvm/llvm-project.git c13a09a462807936f9eb17cc64f53ad7c9e8ddec)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
[507] % 
[507] % clangtk -Os small.c
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /local/suz-local/software/local/clang-trunk/bin/clang-15 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name small.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/local/suz-local/software/emitesting/bugs/20220717-clangtk-m64-O3-build-132128/delta -resource-dir /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0 -I /usr/local/include/csmith -I /local/suz-local/software/local/include -internal-isystem /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Os -fdebug-compilation-dir=/local/suz-local/software/emitesting/bugs/20220717-clangtk-m64-O3-build-132128/delta -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/small-5ae83a.o -x c small.c
1.	<eof> parser at end of file
2.	Optimizer
  #0 0x0000558f263a6a71 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
  #1 0x0000558f263a40e4 SignalHandler(int) Signals.cpp:0:0
  #2 0x00007f92dcd9a980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
  #3 0x0000558f25323098 computeKnownBitsFromAssume(llvm::Value const*, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #4 0x0000558f2531dc21 computeKnownBits(llvm::Value const*, llvm::APInt const&, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #5 0x0000558f2532124f computeKnownBits(llvm::Value const*, llvm::KnownBits&, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #6 0x0000558f2532304a computeKnownBits(llvm::Value const*, unsigned int, (anonymous namespace)::Query const&) ValueTracking.cpp:0:0
  #7 0x0000558f25325a82 llvm::computeKnownBits(llvm::Value const*, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::Instruction const*, llvm::DominatorTree const*, llvm::OptimizationRemarkEmitter*, bool) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2d1aa82)
  #8 0x0000558f25289417 llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c7e417)
  #9 0x0000558f25288e0d llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c7de0d)
 #10 0x0000558f252890d2 llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c7e0d2)
 #11 0x0000558f25288e0d llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c7de0d)
 #12 0x0000558f25289248 llvm::ScalarEvolution::GetMinTrailingZerosImpl(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c7e248)
 #13 0x0000558f25288e0d llvm::ScalarEvolution::GetMinTrailingZeros(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c7de0d)
 #14 0x0000558f252a2e92 llvm::ScalarEvolution::getRangeRef(llvm::SCEV const*, llvm::ScalarEvolution::RangeSignHint) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c97e92)
 #15 0x0000558f252a5bc0 llvm::ScalarEvolution::isKnownNonNegative(llvm::SCEV const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c9abc0)
 #16 0x0000558f252b3326 llvm::ScalarEvolution::getGEPExpr(llvm::GEPOperator*, llvm::SmallVectorImpl<llvm::SCEV const*> const&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2ca8326)
 #17 0x0000558f252b3591 llvm::ScalarEvolution::createNodeForGEP(llvm::GEPOperator*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2ca8591)
 #18 0x0000558f252980e6 llvm::ScalarEvolution::createSCEVIter(llvm::Value*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2c8d0e6)
 #19 0x0000558f252bb5d2 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb05d2)
 #20 0x0000558f252bc20b llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb120b)
 #21 0x0000558f252bbc8c llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb0c8c)
 #22 0x0000558f252bc20b llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb120b)
 #23 0x0000558f252bb6ed llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb06ed)
 #24 0x0000558f252bc20b llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb120b)
 #25 0x0000558f252bb6ed llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb06ed)
 #26 0x0000558f252bc20b llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb120b)
 #27 0x0000558f252bb5e5 llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb05e5)
 #28 0x0000558f252bc20b llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb120b)
 #29 0x0000558f252bbc8c llvm::ScalarEvolution::computeSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb0c8c)
 #30 0x0000558f252bc20b llvm::ScalarEvolution::getSCEVAtScope(llvm::SCEV const*, llvm::Loop const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2cb120b)
...
clang-15: error: unable to execute command: Segmentation fault
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 15.0.0 (https://github.com/llvm/llvm-project.git c13a09a462807936f9eb17cc64f53ad7c9e8ddec)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
clang-15: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/small-622c80.c
clang-15: note: diagnostic msg: /tmp/small-622c80.sh
clang-15: note: diagnostic msg: 

********************
[508] % 
[508] % cat small.c
int a[1], b, c, d, e, f, g;
int main() {
  int i = 0;
  for (; i < 2; i++)
    for (c = 0; c; c++)
      ;
  if (c)
    for (; e; e++)
      for (i = 0; i < 7; i++)
        for (d = 0; d < 9; d++)
          for (f = 0; f < 7; f++)
            for (g = 0; g < 4; g++) {
              b = a[b];
              b = a[b];
              b = a[b];
            }
  return 0;
}
```

**Comment by xgupta** [comment]
> Compiler Explorer: https://godbolt.org/z/vnos8Toqv

checked the link just now, it is not crashing on the trunk.
