### ISSUE TITLE
Suboptimal instruction sequence when operands are reordered

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#57255]
```c
int foo(int t) {
    return t - (1 - 5 * t);
}

int bar(int t) {
    return t - 1 + 5 * t;
}

int baz(int t) {
    return t + 5 * t - 1;
}
```

riscv64-clang -O3
```
        .text
        .attribute      4, 16
        .attribute      5, "rv64i2p0_m2p0_a2p0_f2p0_d2p0_c2p0"
        .file   "example.c"
        .globl  foo                             # -- Begin function foo
        .p2align        1
        .type   foo,@function
foo:                                    # @foo
# %bb.0:
        slliw   a1, a0, 2
        addw    a1, a1, a0
        addw    a0, a0, a1
        addiw   a0, a0, -1
        ret
.Lfunc_end0:
        .size   foo, .Lfunc_end0-foo
                                        # -- End function
        .globl  bar                             # -- Begin function bar
        .p2align        1
        .type   bar,@function
bar:                                    # @bar
# %bb.0:
        slliw   a1, a0, 2
        addw    a1, a1, a0
        addw    a0, a0, a1
        addiw   a0, a0, -1
        ret
.Lfunc_end1:
        .size   bar, .Lfunc_end1-bar
                                        # -- End function
        .globl  baz                             # -- Begin function baz
        .p2align        1
        .type   baz,@function
baz:                                    # @baz
# %bb.0:
        li      a1, 6
        mulw    a0, a0, a1
        addiw   a0, a0, -1
        ret
.Lfunc_end2:
        .size   baz, .Lfunc_end2-baz
                                        # -- End function
        .ident  "clang version 16.0.0 (https://github.com/llvm/llvm-project.git 06c02d5dbb13f6d2a10eaa75c236f3c61cdf5b91)"
        .section        ".note.GNU-stack","",@progbits
        .addrsig
```

In the last case mulw is generated.

**Comment by topperc** [comment]
The IR for @foo looks silly @rotateright 

```
define dso_local i32 @foo(i32 noundef %0) local_unnamed_addr #0 {
  %2 = mul i32 %0, -5
  %3 = xor i32 %2, -1
  %4 = add i32 %3, %0
  ret i32 %4
}
```

**Comment by topperc** [comment]
The instructions are the same for X86 but the operands are not. The lea for baz uses `2*`. The others use `4*`

**Comment by topperc** [comment]
We do better with Zba. We manage a 2 instruction serial dependency for @baz

```
foo:                                    # @foo
        sh2add  a1, a0, a0
        add     a0, a0, a1
        addi    a0, a0, -1
        ret
bar:                                    # @bar
        sh2add  a1, a0, a0
        add     a0, a0, a1
        addi    a0, a0, -1
        ret
baz:                                    # @baz
        sh1add  a0, a0, a0
        li      a1, -1
        sh1add  a0, a0, a1
        ret
```

**Comment by rotateright** [comment]
> The IR for @foo looks silly @rotateright
> 
> ```
> define dso_local i32 @foo(i32 noundef %0) local_unnamed_addr #0 {
>   %2 = mul i32 %0, -5
>   %3 = xor i32 %2, -1
>   %4 = add i32 %3, %0
>   ret i32 %4
> }
> ```

Yeah, I didn't step through the transforms, but I think we want to reduce all of these to baz() form in IR since that's shortest:
https://alive2.llvm.org/ce/z/oZqFop

That means the backend needs more mul expansion smarts if we are trying to avoid the mul in asm.

**Comment by rotateright** [comment]
> However, X86 generates the same instruction sequence for all three

This comment is not correct:

>         lea     eax, [rdi + 4*rdi]
>         add     eax, edi
...
>         lea     eax, [rdi + 4*rdi]
>         add     eax, edi
...
>         lea     eax, [rdi + 2*rdi]
>         add     eax, eax

In the baz() case, it decomposed as (3*x) + (3*x), but the others were 5*x + x. I don't think that makes a perf difference on any recent CPU, but it does show that we could do better at canonicalizing in codegen too?

**Comment by hiraditya** [comment]
> This comment is not correct:

Yeah, missed it. But w.r.t. performance all three will be similar while for Arm and Riscv there is difference.

> I don't think that makes a perf difference on any recent CPU, but it does show that we could do better at canonicalizing in codegen too?

agreed!

**Comment by vfdff** [comment]
Fixes AArch64 part with https://reviews.llvm.org/D132322

**Comment by rotateright** [comment]
On the IR side, we could generalize the factoring to patterns with no constants:
https://alive2.llvm.org/ce/z/mbsDdE
That's likely better in IR since it eliminates a use of 'x', but it's probably worse in codegen for most targets (especially if they have a 'madd' instruction).

**Comment by rotateright** [comment]
> On the IR side, we could generalize the factoring to patterns with no constants: https://alive2.llvm.org/ce/z/mbsDdE That's likely better in IR since it eliminates a use of 'x', but it's probably worse in codegen for most targets (especially if they have a 'madd' instruction).

On 2nd thought, madd codegen looks fine either way (at least for aarch64):
```
src:
	add	w8, w0, w2
	madd	w0, w0, w1, w8
tgt:
	madd	w8, w0, w1, w0
	add	w0, w8, w2
```

The 'tgt' form with dependent ops might have a longer critical path without madd, but that should be invertible in codegen.

**Comment by rotateright** [comment]
Proposal to improve canonicalization in IR:
https://reviews.llvm.org/D132412

**Comment by rotateright** [comment]
> The IR for @foo looks silly @rotateright

That part should be fixed in IR at least with:
f7ab70cf8df6117312a

D132412 was initially going to change the bar() IR, but that patch ended up fixing another pattern, and we still miss bar().

It's still up to the backend to decompose the mul if that's better for the target.

**Comment by vfdff** [comment]
This issue is still exist for the 2nd function **bar**, https://godbolt.org/z/vjree4xfY

**Comment by vfdff** [comment]
Proposal to improve canonicalization in IR of **bar** , https://reviews.llvm.org/D136623

**Comment by hiraditya** [comment]
> Proposal to improve canonicalization in IR of **bar** , https://reviews.llvm.org/D136623

@vfdff It seems like the patch was abandoned? are you still planning to work on it?

**Comment by tetsuo-cpp** [comment]
> > Proposal to improve canonicalization in IR of **bar** , https://reviews.llvm.org/D136623
> 
> @vfdff It seems like the patch was abandoned? are you still planning to work on it?

@hiraditya I can rebase that change onto trunk and try to getting it in. Would that be helpful?

**Comment by hiraditya** [comment]
yes please.

**Comment by gxyd** [comment]
Hi, is anyone actively working on this issue? I see an open pull request corresponding to this issue, was wondering if it's being actively worked on?

**Comment by vfdff** [comment]
I‘m not working on it, I think it is pleasure you can continue on this as there is no update for a long time @gxyd

**Comment by gxyd** [comment]
Thank you for your reply. I'll get started with it then.

**Comment by gxyd** [comment]
@hiraditya , can you maybe assign the issue to me?

**Comment by dc03** [comment]
> @hiraditya , can you maybe assign the issue to me?

Should probably ask @tetsuo-cpp what their plans for the PR are first.

**Comment by tetsuo-cpp** [comment]
> Should probably ask @tetsuo-cpp what their plans for the PR are first.

@gxyd Go for it! Thanks for working on this. Unfortunately, I got busy and won't have time to spend on getting that PR in.

I'll close the open PR but will leave the branch on my fork in case you want to use it. Although, it's been a while since I rebased so it might not be useful to you.

**Comment by patric-iar** [comment]
Is this issue being worked on, or should it be closed?
Clang-22 seems to do this right for RISCV/32/64 (for the three sample cases):
```
	slli   a1, a0, 3
	slli   a0, a0, 1
	not    a0, a0
	add[w] a0, a0, a1
```
