### ISSUE TITLE
AArch64 GlobalISel double free at `AArch64GenPreLegalizerCombinerHelper::tryCombineAll`

### ISSUE THREAD

**Issue by DataCorrupted** [llvm/llvm-project#57282]
When compiling the following piece of code, AARch64 will have an assertion. It seems when the index is incorrect or invalid it will trigger bug. On LLVM14 it was double free, on latest commit `cfd2c5ce580` it is an assertion failure.

```llvm
; ModuleID = 'PoC.bc'
source_filename = "M"

define void @f() {
BB:
  %A = alloca <32 x i8>, align 32
  %I = insertelement <32 x i8> <i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127>, i8 -128, i64 -1
  store <32 x i8> %I, <32 x i8>* %A, align 32
  ret void
}
```

```llvm
; ModuleID = 'PoC.bc'
source_filename = "M"

define void @f() {
BB:
  %A = alloca <8 x i8>, align 8
  %I = insertelement <8 x i8> <i8 16, i8 16, i8 16, i8 16, i8 16, i8 16, i8 16, i8 16>, i8 -1, i1 true
  store <8 x i8> %I, <8 x i8>* %A, align 8
  ret void
}
```

Here's a report:

```console
llc: /home/peter/aflplusplus-isel/llvm-project/llvm/include/llvm/ADT/SmallVector.h:280: llvm::SmallVectorTemplateCommon::reference llvm::SmallVectorTemplateCommon<llvm::Register>::operator[](llvm::SmallVectorTemplateCommon::size_type) [T = llvm::Register]: Assertion `idx < size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/peter/aflplusplus-isel/llvm-project/build-debug/bin/llc PoC.ll -mtriple=aarch64 -global-isel
1.      Running pass 'Function Pass Manager' on module 'PoC.ll'.
2.      Running pass 'AArch64PreLegalizerCombiner' on function '@f'
 #0 0x00000000030fb20a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:11
 #1 0x00000000030fb3bb PrintStackTraceSignalHandler(void*) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x00000000030f9a06 llvm::sys::RunSignalHandlers() /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Signals.cpp:103:5
 #3 0x00000000030fbae5 SignalHandler(int) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f889724d980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #5 0x00007f889613de87 raise /build/glibc-uZu3wS/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #6 0x00007f889613f7f1 abort /build/glibc-uZu3wS/glibc-2.27/stdlib/abort.c:81:0
 #7 0x00007f889612f3fa __assert_fail_base /build/glibc-uZu3wS/glibc-2.27/assert/assert.c:89:0
 #8 0x00007f889612f472 (/lib/x86_64-linux-gnu/libc.so.6+0x30472)
 #9 0x0000000000e2be09 llvm::SmallVectorTemplateCommon<llvm::Register, void>::operator[](unsigned long) /home/peter/aflplusplus-isel/llvm-project/llvm/include/llvm/ADT/SmallVector.h:0:5
#10 0x000000000357aa6f llvm::CombinerHelper::matchCombineInsertVecElts(llvm::MachineInstr&, llvm::SmallVectorImpl<llvm::Register>&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/GlobalISel/CombinerHelper.cpp:2584:10
#11 0x00000000013027f2 (anonymous namespace)::AArch64GenPreLegalizerCombinerHelper::tryCombineAll(llvm::GISelChangeObserver&, llvm::MachineInstr&, llvm::MachineIRBuilder&) const::$_18::operator()() const /home/peter/aflplusplus-isel/llvm-project/build-debug/lib/Target/AArch64/AArch64GenPreLegalizeGICombiner.inc:1078:12
#12 0x00000000012f9835 (anonymous namespace)::AArch64GenPreLegalizerCombinerHelper::tryCombineAll(llvm::GISelChangeObserver&, llvm::MachineInstr&, llvm::MachineIRBuilder&) const /home/peter/aflplusplus-isel/llvm-project/build-debug/lib/Target/AArch64/AArch64GenPreLegalizeGICombiner.inc:1076:11
#13 0x00000000012f54b1 (anonymous namespace)::AArch64PreLegalizerCombinerInfo::combine(llvm::GISelChangeObserver&, llvm::MachineInstr&, llvm::MachineIRBuilder&) const /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Target/AArch64/GISel/AArch64PreLegalizerCombiner.cpp:383:7
#14 0x000000000356aa60 llvm::Combiner::combineMachineInstrs(llvm::MachineFunction&, llvm::GISelCSEInfo*) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/GlobalISel/Combiner.cpp:147:18
#15 0x00000000012f5179 (anonymous namespace)::AArch64PreLegalizerCombiner::runOnMachineFunction(llvm::MachineFunction&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Target/AArch64/GISel/AArch64PreLegalizerCombiner.cpp:472:3
#16 0x0000000001e9326d llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:85:8
#17 0x00000000025a2256 llvm::FPPassManager::runOnFunction(llvm::Function&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1430:23
#18 0x00000000025a7082 llvm::FPPassManager::runOnModule(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1476:16
#19 0x00000000025a2b29 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1545:23
#20 0x00000000025a269d llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:535:16
#21 0x00000000025a7361 llvm::legacy::PassManager::run(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1672:3
#22 0x0000000000c744b0 compileModule(char**, llvm::LLVMContext&) /home/peter/aflplusplus-isel/llvm-project/llvm/tools/llc/llc.cpp:737:41
#23 0x0000000000c72832 main /home/peter/aflplusplus-isel/llvm-project/llvm/tools/llc/llc.cpp:418:13
#24 0x00007f8896120c87 __libc_start_main /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:344:0
#25 0x0000000000c7203a _start (/home/peter/aflplusplus-isel/llvm-project/build-debug/bin/llc+0xc7203a)
Aborted
```

**Comment by fhahn** [comment]
cc @aemerson @ornata

**Comment by DataCorrupted** [comment]
I think this is related to #57406 , the stack trace and behavior seems similar: Double free on release, OOB on debug. Maybe it's a architectural independent bug in LLVM. 

I just verified that the seed I put in #57406 also crashes AArch64's GlobalIsel: https://llvm.godbolt.org/z/4xn5TY43M

**Comment by aemerson** [comment]
The cause is that the index for the `insertelement` is out of bounds (-1), which normally should be folded into undef. We should fix the crashing combine, but also implement the fold as well.

**Comment by aemerson** [comment]
The combine crash should be fixed in fb60e50c789c

Undef combine is next

**Comment by aemerson** [comment]
https://reviews.llvm.org/D133309 for the undef combine, but this particular crash should be fixed with the earlier commit. Closing.

**Comment by DataCorrupted** [comment]
Thanks for the fix. However, I am afraid it's not fully fixed. The most up-to-date commit still can't pass the test: https://llvm.godbolt.org/z/ovsdfajae

It is giving me `LLVM ERROR: unable to legalize instruction: %1:_(<32 x s8>) = G_INSERT_VECTOR_ELT %2:_, %4:_(s8), %5:_(s64)`.

**Comment by aemerson** [comment]
That's fine, it's failing to compile but it's not a crash, which is the important thing.

If I run the test case with trunk it works, because ToT has ```commit 3dd861818a68b2e0b21d426ee956ec8d69f89c88
Author: Amara Emerson <amara@apple.com>
Date:   Mon Sep 5 16:10:59 2022 +0100

    [GlobalISel] Combine G_INSERT/EXTRACT_VECTOR_ELT with out of bounds indices to undef.
    
    Differential Revision: https://reviews.llvm.org/D133309```

which optimizes away the entire thing. It's likely that godbolt doesn't have the very latest LLVM version.
