### ISSUE TITLE
Epilog vector body missing %resume.val contribution to phi

### ISSUE THREAD

**Issue by peterwaller-arm** [llvm/llvm-project#57912]
I have bisected a case of a checksum failure in a non-trivial internal C++ workload to a recent change, 582f8ef19fe791e66c0bbe090edebfd74ba2b55d (`[LV] Keep track of cost-based ScalarAfterVec in VPWidenPointerInd`, committed Mon Sep 19 18:14:35 2022 +0100).

I have made a minimal IR reproducer, which shows the issue when fed to `bin/opt -passes='function(loop-vectorize),default<O2>' -S` (though `default<O2>` is not necessary to induce the issue, that is what is shown below).

```llvm
target triple = "aarch64"

define void @repro_issue_57912(ptr %arg, i64 %arg1) "target-features"="+sve,+sve2" {
entry:
  br label %loop.body
loop.body:
  %ind = phi i64 [ %ind.next, %loop.body ], [ 0, %entry ]
  %gep = phi ptr [ %gep.next, %loop.body ], [ %arg, %entry ]
  store i8 0, ptr %gep, align 1
  %gep.next = getelementptr inbounds i8, ptr %gep, i64 1
  %ind.next = add nuw nsw i64 %ind, 1
  %cmp = icmp eq i64 %ind, %arg1
  br i1 %cmp, label %exit, label %loop.body
exit:
  ret void
}
```

On main this produces the following epilog loop:

```llvm
vec.epilog.vector.body:                           ; preds = %vec.epilog.vector.body, %vec.epilog.ph
  %pointer.phi11 = phi ptr [ %arg, %vec.epilog.ph ], [ %ptr.ind12, %vec.epilog.vector.body ]
  %index10 = phi i64 [ %vec.epilog.resume.val, %vec.epilog.ph ], [ %index.next16, %vec.epilog.vector.body ]
  store <vscale x 8 x i8> zeroinitializer, ptr %pointer.phi11, align 1
  %index.next16 = add nuw i64 %index10, %2
  %ptr.ind12 = getelementptr i8, ptr %pointer.phi11, i64 %2
  %9 = icmp eq i64 %index.next16, %n.vec6
  br i1 %9, label %vec.epilog.middle.block, label %vec.epilog.vector.body, !llvm.loop !2
```

With a revert of 582f8ef19fe791e66c0bbe090edebfd74ba2b55d on main, I get the following, for which the workload does not have a checksum failure:

```llvm
vec.epilog.vector.body:                           ; preds = %vec.epilog.vector.body, %vec.epilog.ph
  %index8 = phi i64 [ %vec.epilog.resume.val, %vec.epilog.ph ], [ %index.next10, %vec.epilog.vector.body ]
  %next.gep9 = getelementptr i8, ptr %arg, i64 %index8
  store <vscale x 8 x i8> zeroinitializer, ptr %next.gep9, align 1
  %index.next10 = add nuw i64 %index8, %2
  %9 = icmp eq i64 %index.next10, %n.vec4
  br i1 %9, label %vec.epilog.middle.block, label %vec.epilog.vector.body, !llvm.loop !2
```

What I see is that in the broken case, the `%pointer.phi11` phi begins at `%arg`, and in the working case, the equivalent store destination `%next.gep9` begins at `%arg + %vec.epilog.resume.val`. So it appears there is a problem with how the phi has been constructed in this epilog body, and it is not commencing where the main vector body has left off as it should.

cc @fhahn - My guess is that the patch is not at fault but has revealed a bug in epilog vectorization, do you concur? Would it be possible to revert your patch until a fix can be found? Thanks in advance.

**Comment by peterwaller-arm** [comment]
I see this went into the 15.0.1 branch in b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf, and the workload is broken there. I can confirm reverting b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf on release/15.x does fix the workload.

**Comment by tru** [comment]
@fhahn thoughts?

**Comment by fhahn** [comment]
> cc @fhahn - My guess is that the patch is not at fault but has revealed a bug in epilog vectorization, do you concur? 

Hm, it looks like unfortunately dependent code has been changed quite a lot since 151c14435037072af795f2bec7626e3951d30965 which b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf effectively reverts.  Now we run into a case where lowering didn't expect/support the behavior pre-151c14435037072af795f2bec7626e3951d30965 any longer. I'll track down the code that needs further updating in the next few hours.

**Comment by fhahn** [comment]
I pushed a fix that should restore the original behavior pre https://github.com/llvm/llvm-project/commit/151c14435037072af795f2bec7626e3951d30965 for the current code including the revert. Please let me know if you see any further issues.

**Comment by tru** [comment]
@fhahn do we need to anything? Sorry jumped the gun on reopening before I understood if we had to do anything in the 15.x branch.

**Comment by peterwaller-arm** [comment]
I've tested the workload on main and on release/15.x, it's fixed on main but still broken on the release/15.x branch.

Cherry picking 2c692d891ed639779b1c4b504ca63037bbacc0e8 does fix the release branch, but it conflicts on a test case.

**Comment by fhahn** [comment]
/cherry-pick 05b3493819fa8aba1eb7510afbcb80a64148beb6 17167005d532dce35ade3a47a0403ffaa7fff6ff 2c692d891ed639779b1c4b504ca63037bbacc0e8

**Comment by fhahn** [comment]
@peterwaller-arm @tru https://github.com/llvm/llvm-project-release-prs/pull/177 should have the test changes + functional fix picked.

**Comment by peterwaller-arm** [comment]
1) The reproducer above (i.e. that code with `bin/opt -passes='function(loop-vectorize),default<O2>' -S`) still appears to be broken, and seems to have identical output on main and release-15.x.
2) The original private reproducer works on main.
3) The original private reproducer is broken on release-15.x.

Below is the IR I see with `repro_issue_57912` (on main & release/15.x). I don't yet know why the private reproducer is not asserting with a checksum error on main.

What I see: `%pointer.phi11 ` still begins at `%arg`, for both the main branch and release-15.x.

```llvm
vec.epilog.vector.body:                           ; preds = %vec.epilog.vector.body, %vec.epilog.ph
  %pointer.phi11 = phi ptr [ %arg, %vec.epilog.ph ], [ %ptr.ind12, %vec.epilog.vector.body ]
  %index10 = phi i64 [ %vec.epilog.resume.val, %vec.epilog.ph ], [ %index.next16, %vec.epilog.vector.body ]
  %31 = call i64 @llvm.vscale.i64()
  %32 = mul i64 %31, 8
  %33 = mul i64 %32, 1
  %34 = mul i64 1, %33
  %35 = mul i64 %32, 0
  %.splatinsert13 = insertelement <vscale x 8 x i64> poison, i64 %35, i32 0
  %.splat14 = shufflevector <vscale x 8 x i64> %.splatinsert13, <vscale x 8 x i64> poison, <vscale x 8 x i32> zeroinitializer
  %36 = call <vscale x 8 x i64> @llvm.experimental.stepvector.nxv8i64()
  %37 = add <vscale x 8 x i64> %.splat14, %36
  %vector.gep15 = mul <vscale x 8 x i64> %37, shufflevector (<vscale x 8 x i64> insertelement (<vscale x 8 x i64> poison, i64 1, i32 0), <vscale x 8 x i64> poison, <vscale x 8 x i32> zeroinitializer)
  %38 = getelementptr i8, ptr %pointer.phi11, <vscale x 8 x i64> %vector.gep15
  %39 = extractelement <vscale x 8 x ptr> %38, i32 0
  %40 = getelementptr i8, ptr %39, i32 0
  store <vscale x 8 x i8> zeroinitializer, ptr %40, align 1
```

**Comment by fhahn** [comment]
Could you double-check current `main` again? Here's a godbolt link for your reproducer (https://llvm.godbolt.org/z/M1sGY34of) and it generates the following code for the epilogue vector body. Perhaps I am using the original reproducer wrong?

```
vec.epilog.vector.body:                           ; preds = %vec.epilog.vector.body, %vec.epilog.ph
  %index8 = phi i64 [ %vec.epilog.resume.val, %vec.epilog.ph ], [ %index.next10, %vec.epilog.vector.body ]
  %next.gep9 = getelementptr i8, ptr %arg, i64 %index8
  store <vscale x 8 x i8> zeroinitializer, ptr %next.gep9, align 1
  %index.next10 = add nuw i64 %index8, %2
  %9 = icmp eq i64 %index.next10, %n.vec4
  br i1 %9, label %vec.epilog.middle.block, label %vec.epilog.vector.body, !llvm.loop !2
```

Also, the fix hasn't been cherry-picked on `release/15.x` yet. Did you check the original reproducer with the code from https://github.com/llvm/llvm-project-release-prs/pull/177?

**Comment by peterwaller-arm** [comment]
You spotted the contradiction, thanks! I was testing the release branch and not the cherry-pick PR, sorry. Confirmed that the workload looks good.

**Comment by fhahn** [comment]
@peterwaller-arm That's great news, thanks for checking!
