### ISSUE TITLE
libomp.so.5 fails to link with `symbol omp_set_affinity_format_ has undefined version OMP_5.0`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#58345]
Started to regress today:
```
FAILED: openmp/runtime/src/libomp.so.5 
: && "/build/llvm-toolchain-snapshot-16~++20221013034023+d8cab3f40707/build-llvm/./bin/clang" --target=x86_64-pc-linux-gnu -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/llvm-toolchain-snapshot-16~++20221013034023+d8cab3f40707/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -ffile-prefix-map=/build/llvm-toolchain-snapshot-16~++20221013034023+d8cab3f40707/= -no-canonical-prefixes -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-enum-constexpr-conversion -Wno-extra -Wno-pedantic -O3 -DNDEBUG  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--build-id -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=gold  -Wl,--warn-shared-textrel -Wl,--as-needed -static-libgcc -Wl,-z,noexecstack -shared -Wl,-soname,libomp.so.5 -o openmp/runtime/src/libomp.so.5 openmp/runtime/src/CMakeFiles/omp.dir/kmp_alloc.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_atomic.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_itt.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_environment.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_global.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_io.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_runtime.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_settings.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_str.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_tasking.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_threadprivate.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_utility.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_barrier.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_wait_release.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_affinity.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_dispatch.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_lock.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_sched.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/z_Linux_util.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/thirdparty/ittnotify/ittnotify_static.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_taskdeps.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_cancel.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_cdecl.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_extra.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_version.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/z_Linux_asm.S.o  -lm  -ldl && cd "/build/llvm-toolchain-snapshot-16~++20221013034023+d8cab3f40707/build-llvm/runtimes/runtimes-bins/openmp/runtime/src" && /usr/bin/cmake -E create_symlink libomp.so.5 libgomp.so && /usr/bin/cmake -E create_symlink libomp.so.5 libiomp5.so
/usr/bin/ld.gold: error: symbol omp_set_affinity_format_ has undefined version VERSION
/usr/bin/ld.gold: error: symbol omp_set_affinity_format_ has undefined version OMP_5.0
/usr/bin/ld.gold: error: symbol GOMP_parallel has undefined version GOMP_4.0
/usr/bin/ld.gold: error: symbol omp_get_ancestor_thread_num_ has undefined version OMP_3.0
/usr/bin/ld.gold: error: symbol omp_get_partition_place_nums_ has undefined version OMP_4.5
/usr/bin/ld.gold: error: symbol omp_get_num_devices_ has undefined version OMP_4.0
/usr/bin/ld.gold: error: symbol omp_get_wtick_ has undefined version OMP_2.0
/usr/bin/ld.gold: error: symbol omp_in_final_ has undefined version OMP_3.1
/usr/bin/ld.gold: error: symbol omp_get_thread_num_ has undefined version OMP_1.0
/usr/bin/ld.gold: error: symbol GOMP_loop_ordered_start has undefined version GOMP_5.0
/usr/bin/ld.gold: error: symbol GOMP_parallel_loop_nonmonotonic_dynamic has undefined version GOMP_4.5
/usr/bin/ld.gold: error: symbol GOMP_single_start has undefined version GOMP_1.0
/usr/bin/ld.gold: error: symbol GOMP_loop_ull_ordered_runtime_next has undefined version GOMP_2.0
/usr/bin/ld.gold: error: symbol GOMP_taskyield has undefined version GOMP_3.0
/usr/bin/ld.gold: error: symbol GOMP_free has undefined version GOMP_5.0.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sylvestre** [comment]
https://llvm-jenkins.debian.net/job/llvm-toolchain-focal-binaries/architecture=amd64,distribution=focal,label=amd64/356/

**Comment by jhuber6** [comment]
This should've been solved by 096f93e73dc3f88636cdcb57515e3732385b452d. The problem started after https://reviews.llvm.org/D135402 so we had to change the CMake.

**Comment by ms178** [comment]
@jhuber6 I've just tried to compile ToT with Clang-15 (5d9fa4d16e0e75c069dcbfec30005974c46635d1) as system compiler, but I get:

```
[1331/1983] Linking C shared library openmp/runtime/src/libomp.so
FAILED: openmp/runtime/src/libomp.so 
: && /home/marcus/Downloads/llvm-git/src/llvm-project/build/./bin/clang --target=x86_64-pc-linux-gnu -fPIC -O3 -march=native -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fno-math-errno -fno-trapping-math -funroll-loops -falign-functions=32 -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -mprefer-vector-width=256 -flto=thin -fPIC -fno-semantic-interposition -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-enum-constexpr-conversion -Wno-extra -Wno-pedantic -O3 -DNDEBUG  -Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto=thin -fuse-ld=lld -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=lld -Wl,--color-diagnostics  -Wl,--warn-shared-textrel -Wl,--as-needed -static-libgcc -Wl,-z,noexecstack -shared -Wl,-soname,libomp.so -o openmp/runtime/src/libomp.so openmp/runtime/src/CMakeFiles/omp.dir/kmp_alloc.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_atomic.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_itt.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_environment.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_global.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_io.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_runtime.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_settings.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_str.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_tasking.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_threadprivate.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_utility.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_barrier.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_wait_release.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_affinity.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_dispatch.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_lock.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_sched.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/z_Linux_util.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/thirdparty/ittnotify/ittnotify_static.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_taskdeps.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_cancel.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_cdecl.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_extra.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/kmp_version.cpp.o openmp/runtime/src/CMakeFiles/omp.dir/z_Linux_asm.S.o  -lm  -ldl && cd /home/marcus/Downloads/llvm-git/src/llvm-project/build/runtimes/runtimes-bins/openmp/runtime/src && /usr/bin/cmake -E create_symlink libomp.so libgomp.so && /usr/bin/cmake -E create_symlink libomp.so libiomp5.so
clang-16: warning: argument unused during compilation: '-mllvm -extra-vectorizer-passes' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-cond-stores-vec' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -slp-vectorize-hor-store' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-loopinterchange' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-loop-distribute' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-unroll-and-jam' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-loop-flatten' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -interleave-small-loop-scalar-reduction' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -unroll-runtime-multi-exit' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -aggressive-ext-opt' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mharden-sls=none' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -extra-vectorizer-passes' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-cond-stores-vec' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -slp-vectorize-hor-store' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-loopinterchange' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-loop-distribute' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-unroll-and-jam' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -enable-loop-flatten' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -interleave-small-loop-scalar-reduction' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -unroll-runtime-multi-exit' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-mllvm -aggressive-ext-opt' [-Wunused-command-line-argument]
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol ompc_set_affinity_format@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol ompc_capture_affinity@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol ompc_display_affinity@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol omp_get_affinity_format@OMP_5.0 has undefined version OMP_5.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol ompc_get_affinity_format@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol omp_capture_affinity@OMP_5.0 has undefined version OMP_5.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol omp_set_affinity_format@OMP_5.0 has undefined version OMP_5.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o: symbol omp_display_affinity@OMP_5.0 has undefined version OMP_5.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_ull_dynamic_next@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_ull_nonmonotonic_guided_start@GOMP_4.5 has undefined version GOMP_4.5
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_ull_static_next@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_static_start@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_single_copy_end@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_teams_reg@GOMP_5.0 has undefined version GOMP_5.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_teams_reg@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_ull_ordered_dynamic_start@@VERSION has undefined version VERSION
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_end_nowait@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_target_update@GOMP_4.0 has undefined version GOMP_4.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_ull_ordered_dynamic_next@GOMP_2.0 has undefined version GOMP_2.0
ld.lld: error: openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_loop_doacross_runtime_start@GOMP_4.5 has undefined version GOMP_4.5
ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)

```

**Comment by jhuber6** [comment]
The problem is that `lld` changed to reject undefined symbols in version scripts by default. This should've been fixed because every use of `--version-script` in `libomp` now uses `--undefined-version` to use the old behavior. Can you try a completely clean build? It might not have updated the linker command. This was a problem earlier in one of the OpenMP buildbots and it was resolved this morning.

**Comment by ms178** [comment]
With Clang-16 (b13f7f9c06604110709a968a2fece4b8d5192708), fresh files, using LLD, I now get:

```
[2766/4614] Linking CXX shared library lib/libLTO.so.16git
FAILED: lib/libLTO.so.16git 
: && /usr/bin/clang++ -fPIC -O3 -march=native -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fno-math-errno -fno-trapping-math -funroll-loops -falign-functions=32 -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -mprefer-vector-width=256 -flto=thin -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -flto=thin -O3 -DNDEBUG  -Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fuse-ld=lld -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=lld -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-cache-dir=/home/marcus/Downloads/llvm-git/src/llvm-project/build/lto.cache   -Wl,--gc-sections  -Wl,--version-script,"/home/marcus/Downloads/llvm-git/src/llvm-project/build/tools/lto/LTO.exports" -shared -Wl,-soname,libLTO.so.16git -o lib/libLTO.so.16git tools/lto/CMakeFiles/LTO.dir/LTODisassembler.cpp.o tools/lto/CMakeFiles/LTO.dir/lto.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVM-16git.so && :
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMCreateDisasm' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMCreateDisasmCPU' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMDisasmDispose' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMDisasmInstruction' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMSetDisasmOptions' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMCreateDisasmCPUFeatures' failed: symbol not defined
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by jhuber6** [comment]
I got that as well, it went away with a completely clean build. That being said, I think I'm just going to revert these patches as it's causing a lot of problems.

**Comment by ms178** [comment]
Someone did just that: https://github.com/llvm/llvm-project/commit/88da0de14f135bee034b286cc736dacd6274e77d

**Comment by jhuber6** [comment]
Yes, they were discussing the issue on the original commit and mine. It should work now so hopefully we can close this issue.

**Comment by ms178** [comment]
Unfortunately, even with the revert, I still see the last mentioned symbol errors. :(

**Comment by jhuber6** [comment]
> Unfortunately, even with the revert, I still see the last mentioned symbol errors. :(

You'll probably need a completely clean build, try deleting your build directory and any previous installations.

**Comment by ms178** [comment]
I finally got a working build today. :) Compiling with Clang-15 went fine after all.

**Comment by jhuber6** [comment]
Good to hear, hopefully we can fix this more correctly in the future.

**Comment by carlosgalvezp** [comment]
Hi! I'm getting the same error as above in latest trunk, reported a new issue [here](https://github.com/llvm/llvm-project/issues/59488). Unfortunately it doesn't go away with a clean build. Do you have any suggestions on how to fix it?
