### ISSUE TITLE
[libc++] timeout `notify_all_at_thread_exit_lwg3343.pass.cpp` test

### ISSUE THREAD

**Issue by fsb4000** [llvm/llvm-project#60450]
```
TIMEOUT: apple-libc++-backdeployment.cfg.in :: std/thread/thread.condition/notify_all_at_thread_exit_lwg3343.pass.cpp
```
might be a buggy test

**Comment by fsb4000** [comment]
temporary fixed by https://github.com/llvm/llvm-project/commit/70b716db965af2c34726e484914f6d65e18f4b40

**Comment by mordante** [comment]
FYI the LWG3343 error is still flaky. I have a "fix" https://reviews.llvm.org/D143816
