### ISSUE TITLE
clang++ (aarch64) Backend crash when building qgis

### ISSUE THREAD

**Issue by hmartinez82** [llvm/llvm-project#60681]
```console
clang version 15.0.7
Target: aarch64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clangarm64/bin
```
Clang is crashing when building QGis in the MSYS2 / CLANGARM64 environment. This does not happen in the CLANG64 environment.

```console
Building CXX object src/core/CMakeFiles/qgis_core.dir/qgsexpression_texts.cpp.obj
FAILED: src/core/CMakeFiles/qgis_core.dir/qgsexpression_texts.cpp.obj
C:\msys64\clangarm64\bin\clang++.exe -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DTEST_DATA_DIR=\"C:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/tests/testdata\" -DWITH_COPC -DWITH_EPT -D_HAVE_WINDOWS_H_ -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR -Dqgis_core_EXPORTS -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64/src/core/qgis_core_autogen/include -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64 -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/poly2tri -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/ept -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/copc -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64/src/core -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/3d -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/annotations -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/auth -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/browser -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/callouts -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/classification -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/diagram -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/dxf -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/editform -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/effects -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/elevation -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/expression -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/externalstorage -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/fieldformatter -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geometry -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geocms -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geocms/geonode -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geocoding -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/gps -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/labeling -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/layertree -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/layout -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/locator -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/maprenderer -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/mesh -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/metadata -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/network -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/numericformats -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/pal -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/plot -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/pointcloud -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/pointcloud/expression -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/processing -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/processing/models -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/proj -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/project -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/arcgis -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/memory -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/gdal -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/ogr -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/meshmemory -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/raster -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/renderer -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/scalebar -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/settings -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/symbology -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/textrenderer -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/validity -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/vector -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/vectortile -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/nlohmann -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/kdbush/include -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/nmea -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/rtree/include -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/meshOptimizer -isystem C:/msys64/clangarm64/include/QtCore -isystem C:/msys64/clangarm64/share/qt5/mkspecs/win32-clang-g++ -isystem C:/msys64/clangarm64/include/QtGui -isystem C:/msys64/clangarm64/include/QtXml -isystem C:/msys64/clangarm64/include/QtWidgets -isystem C:/msys64/clangarm64/include/QtSvg -isystem C:/msys64/clangarm64/include/QtPrintSupport -isystem C:/msys64/clangarm64/include/QtNetwork -isystem C:/msys64/clangarm64/include/QtSql -isystem C:/msys64/clangarm64/include/QtConcurrent -isystem C:/msys64/clangarm64/include/Qca-qt5/QtCrypto -isystem C:/msys64/clangarm64/include/qt5keychain -isystem C:/msys64/clangarm64/include/QtSerialPort -isystem C:/msys64/clangarm64/include/QtPositioning -O2 -pipe -DQWT_POLAR_VERSION=0x060200 -Wno-ignored-attributes -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wnon-virtual-dtor -Wno-redundant-move -Wno-misleading-indentation -Wreturn-type-c-linkage -Woverloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O3 -DNDEBUG -fvisibility=hidden -std=gnu++17 -O1 -MD -MT src/core/CMakeFiles/qgis_core.dir/qgsexpression_texts.cpp.obj -MF src\core\CMakeFiles\qgis_core.dir\qgsexpression_texts.cpp.obj.d -o src/core/CMakeFiles/qgis_core.dir/qgsexpression_texts.cpp.obj -c C:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64/src/core/qgsexpression_texts.cpp
fatal error: error in backend: SEH unwind data splitting not yet implemented
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: C:\\msys64\\clangarm64\\bin\\clang++.exe -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DTEST_DATA_DIR=\"C:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/tests/testdata\" -DWITH_COPC -DWITH_EPT -D_HAVE_WINDOWS_H_ -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR -Dqgis_core_EXPORTS -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64/src/core/qgis_core_autogen/include -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64 -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/poly2tri -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/ept -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/copc -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64/src/core -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/3d -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/annotations -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/auth -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/browser -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/callouts -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/classification -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/diagram -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/dxf -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/editform -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/effects -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/elevation -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/expression -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/externalstorage -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/fieldformatter -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geometry -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geocms -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geocms/geonode -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/geocoding -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/gps -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/labeling -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/layertree -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/layout -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/locator -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/maprenderer -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/mesh -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/metadata -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/network -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/numericformats -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/pal -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/plot -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/pointcloud -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/pointcloud/expression -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/processing -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/processing/models -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/proj -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/project -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/arcgis -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/memory -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/gdal -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/ogr -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/providers/meshmemory -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/raster -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/renderer -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/scalebar -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/settings -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/symbology -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/textrenderer -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/validity -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/vector -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/src/core/vectortile -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/nlohmann -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/kdbush/include -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/nmea -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/rtree/include -IC:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/qgis-3.28.3/external/meshOptimizer -isystem C:/msys64/clangarm64/include/QtCore -isystem C:/msys64/clangarm64/share/qt5/mkspecs/win32-clang-g++ -isystem C:/msys64/clangarm64/include/QtGui -isystem C:/msys64/clangarm64/include/QtXml -isystem C:/msys64/clangarm64/include/QtWidgets -isystem C:/msys64/clangarm64/include/QtSvg -isystem C:/msys64/clangarm64/include/QtPrintSupport -isystem C:/msys64/clangarm64/include/QtNetwork -isystem C:/msys64/clangarm64/include/QtSql -isystem C:/msys64/clangarm64/include/QtConcurrent -isystem C:/msys64/clangarm64/include/Qca-qt5/QtCrypto -isystem C:/msys64/clangarm64/include/qt5keychain -isystem C:/msys64/clangarm64/include/QtSerialPort -isystem C:/msys64/clangarm64/include/QtPositioning -O2 -pipe -DQWT_POLAR_VERSION=0x060200 -Wno-ignored-attributes -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wnon-virtual-dtor -Wno-redundant-move -Wno-misleading-indentation -Wreturn-type-c-linkage -Woverloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O3 -DNDEBUG -fvisibility=hidden -std=gnu++17 -O1 -MD -MT src/core/CMakeFiles/qgis_core.dir/qgsexpression_texts.cpp.obj -MF src\\core\\CMakeFiles\\qgis_core.dir\\qgsexpression_texts.cpp.obj.d -o src/core/CMakeFiles/qgis_core.dir/qgsexpression_texts.cpp.obj -c C:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64/src/core/qgsexpression_texts.cpp
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'C:/Dev/Github/MINGW-packages/mingw-w64-qgis/src/build-CLANGARM64/src/core/qgsexpression_texts.cpp'.
4.      Running pass 'AArch64 Assembly Printer' on function '@"_ZZN13QgsExpression16initFunctionHelpEvENK3$_0clEv"'
Exception Code: 0xE0000046
 #0 0x00007ffd04bf8d24 (C:\Windows\System32\KERNELBASE.dll+0x78d24)
 #1 0x00007ffc8798451c llvm::CrashRecoveryContext::HandleExit(int) (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x8451c)
 #2 0x00007ffc87a51028 llvm::sys::Process::Exit(int, bool) (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x151028)
 #3 0x00007ff66d5f6314 llvm::InitializeAllAsmPrinters() (C:\msys64\clangarm64\bin\clang++.exe+0x6314)
 #4 0x00007ffc879953f4 llvm::report_fatal_error(llvm::Twine const&, bool) (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x953f4)
 #5 0x00007ffc879952d4 llvm::report_fatal_error(char const*, bool) (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x952d4)
 #6 0x00007ffc88e336e4 llvm::Win64EH::ARM64UnwindEmitter::Emit(llvm::MCStreamer&) const (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x15336e4)
 #7 0x00007ffc8827aa88 llvm::WinException::endFuncletImpl() (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x97aa88)
 #8 0x00007ffc8827a714 llvm::WinException::endFunction(llvm::MachineFunction const*) (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x97a714)
 #9 0x00007ffc882209a0 llvm::AsmPrinter::emitFunctionBody() (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x9209a0)
#10 0x00007ffc893480a8 LLVMInitializeAArch64AsmPrinter (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x1a480a8)
#11 0x00007ffc87dbf97c llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (C:\msys64\clangarm64\bin\libLLVM-15.dll+0x4bf97c)
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 15.0.7
Target: aarch64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clangarm64/bin
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:/msys64/tmp/qgsexpression_texts-33606e.cpp
clang++: note: diagnostic msg: C:/msys64/tmp/qgsexpression_texts-33606e.sh
clang++: note: diagnostic msg:

********************
ninja: build stopped: subcommand failed
```

The only way I can repro this is to try to build `mingw-w64-qgis`  in a CLANGARM64 envrionment in MSYS2.
The crash occurs around file 7239

The two files that the crash suggest to add to the bug report are: https://www.dropbox.com/sh/afep37myphw5mnx/AAAUutJHr2EMP0YgMSxhciLua?dl=0

**Comment by hmartinez82** [comment]
It seems this was fixed in ? https://bugs.llvm.org/show_bug.cgi?id=40311 / https://reviews.llvm.org/D56813
How can I find out which version of LLVM has this fix?

**Comment by DavidSpickett** [comment]
Sounds like it was only partially fixed, by avoiding some situation where you would need "unwind data splitting".

That change was first released in 8.0 - https://github.com/llvm/llvm-project/commit/2f1402b6cb9827593b9096ee1f4368baff9d6774 / https://github.com/llvm/llvm-project/issues/39658.

I assume we still do not support unwind data splitting. Is that correct @efriedma-quic ?

**Comment by efriedma-quic** [comment]
https://reviews.llvm.org/D130049 will be in LLVM 16, I think.

**Comment by hmartinez82** [comment]
I can confirm that LLVM 16 solved this issue. 🚀
