### ISSUE TITLE
[SLPVectorizer] compareCmp is not strict weak ordering 

### ISSUE THREAD

**Issue by danlark1** [llvm/llvm-project#63141]
After submitting https://reviews.llvm.org/D150264, we found that vectorizeCmpInsts, the `compareCmp<false>` is not strict weak ordering. For example, there is no condition for IsDeleted(CI1) and LEPreds/GEPreds are looking in different directions which might violate transitivity of equivalence. As well as `if (I1->getParent() != I2->getParent())` condition as for a, b, c we might have `!comp(a, b), !comp(b, a), !comp(b, c), !comp(c, b)` but `comp(a, c)` as getParent for them might be equal.

This function is complicated and I could not figure out the right fix

```diff
template <bool IsCompatibility>
static bool compareCmp(Value *V, Value *V2, TargetLibraryInfo &TLI,
                       function_ref<bool(Instruction *)> IsDeleted) {
  auto *CI1 = cast<CmpInst>(V);
  auto *CI2 = cast<CmpInst>(V2);
  if (IsDeleted(CI2) || !isValidElementType(CI2->getType()))
    return false;
+ if (IsDeleted(CI1) || !isValidElementType(CI1->getType()))
+   return true;
  if (CI1->getOperand(0)->getType()->getTypeID() <
      CI2->getOperand(0)->getType()->getTypeID())
    return !IsCompatibility;
  if (CI1->getOperand(0)->getType()->getTypeID() >
      CI2->getOperand(0)->getType()->getTypeID())
    return false;
  CmpInst::Predicate Pred1 = CI1->getPredicate();
  CmpInst::Predicate Pred2 = CI2->getPredicate();
  CmpInst::Predicate SwapPred1 = CmpInst::getSwappedPredicate(Pred1);
  CmpInst::Predicate SwapPred2 = CmpInst::getSwappedPredicate(Pred2);
  CmpInst::Predicate BasePred1 = std::min(Pred1, SwapPred1);
  CmpInst::Predicate BasePred2 = std::min(Pred2, SwapPred2);
  if (BasePred1 < BasePred2)
    return !IsCompatibility;
  if (BasePred1 > BasePred2)
    return false;
  // Compare operands.
+ // Likely a violation here as well
  bool LEPreds = Pred1 <= Pred2;
  bool GEPreds = Pred1 >= Pred2;
  for (int I = 0, E = CI1->getNumOperands(); I < E; ++I) {
    auto *Op1 = CI1->getOperand(LEPreds ? I : E - I - 1);
    auto *Op2 = CI2->getOperand(GEPreds ? I : E - I - 1);
    if (Op1->getValueID() < Op2->getValueID())
      return !IsCompatibility;
    if (Op1->getValueID() > Op2->getValueID())
      return false;
    if (auto *I1 = dyn_cast<Instruction>(Op1))
      if (auto *I2 = dyn_cast<Instruction>(Op2)) {
        if (I1->getParent() != I2->getParent())
-          return false;
+          return I1->getParent() < I2->getParent();
        InstructionsState S = getSameOpcode({I1, I2}, TLI);
        if (S.getOpcode())
          continue;
+       // Likely a violation here as well
        return false;
      }
  }
  return IsCompatibility;
}
```

**Comment by alexey-bataev** [comment]
The reproducer is required

**Comment by danlark1** [comment]
Building llvm with trunk libcxx and `-D_LIBCPP_DEBUG_LEVEL=2` and running all tests result for me in

```
   @     0x55e785a41c5a        128  std::__u::__stable_sort_impl<>()
    @     0x55e785a08ce6        160  tryToVectorizeSequence<>()
    @     0x55e785a29fff        256  llvm::SLPVectorizerPass::vectorizeCmpInsts<>()
    @     0x55e785a004ef        736  llvm::SLPVectorizerPass::vectorizeChainsInBlock()
    @     0x55e7859fe291       4320  llvm::SLPVectorizerPass::runImpl()
    @     0x55e7859fdba6        192  llvm::SLPVectorizerPass::run()
    @     0x55e784a6c432         32  llvm::detail::PassModel<>::run()
    @     0x55e786321a55        224  llvm::PassManager<>::run()
    @     0x55e783fee652         32  llvm::detail::PassModel<>::run()
    @     0x55e786324fe9        320  llvm::ModuleToFunctionPassAdaptor::run()
    @     0x55e7832f9ed2         32  llvm::detail::PassModel<>::run()
    @     0x55e786320d75        224  llvm::PassManager<>::run()
```

**Comment by alexey-bataev** [comment]
Fixed in f3ebd88064d7f1c36a8272b3e5f7d53501c3f53b

**Comment by alexey-bataev** [comment]
a8f1a3e025c9

**Comment by danlark1** [comment]
I still see failures when building llvm with libc++ from head with debug mode in llvm/llvm-project/llvm/test/Transforms/SLPVectorizer/X86/poison-element-shuffle.ll.test

**Comment by alexey-bataev** [comment]
> I still see failures when building llvm with libc++ from head with debug mode in llvm/llvm-project/llvm/test/Transforms/SLPVectorizer/X86/poison-element-shuffle.ll.test

I will check

**Comment by alexey-bataev** [comment]
> I still see failures when building llvm with libc++ from head with debug mode in llvm/llvm-project/llvm/test/Transforms/SLPVectorizer/X86/poison-element-shuffle.ll.test

Unable to reproduce, actually compareCmp is never called for this test

**Comment by danlark1** [comment]
Thanks, see no more issues

**Comment by akuegel** [comment]
We are still hitting the assert for the sort that uses the CMP comparator. I added a comment on https://github.com/llvm/llvm-project/commit/a8f1a3e025c905f015a622809e58b03f09b7a58e with a possible fix, but since I don't actually know this code, I am not sure whether it is correct.

**Comment by alexey-bataev** [comment]
Will double check once back from the vacation.

**Comment by akuegel** [comment]
Thank you. I also uploaded a reproducer here: https://github.com/akuegel/llvm-project/blob/main/llvm/test/Transforms/SLPVectorizer/NVPTX/reproducer.ll

**Comment by alexey-bataev** [comment]
Looks like a corner case for cmp comparison, added explicit check for equal instruction opcodes, it should fix the issue. Will commit soon.

**Comment by alexey-bataev** [comment]
Fixed in 58a2c4e2f24ffce3966c3988d1a4ca7b04c52244

**Comment by alexey-bataev** [comment]
Follow up 00edad17c29d9fb24132def1414e73384e6ba4c3

**Comment by akuegel** [comment]
Thank you Alexey :)
