### ISSUE TITLE
orc::InProcessMemoryMapper makes too many memory mappings

### ISSUE THREAD

**Issue by gbaraldi** [llvm/llvm-project#63236]
First seen in https://github.com/JuliaLang/julia/pull/49745, but to summarize, InProcessMemoryMapper calls `mprotect` many many times on `mmap`ed memory, so many times that for a non trivial workload we go past `/proc/sys/vm/max_map_count` leading to a `ENOMEM` error.

**Comment by lhames** [comment]
Within the `InProcessMemoryMapper` we make no attempt to keep permissions contiguous.

I _think_ the OS should be able to coalesce adjacent mappings. If that's the case then a simple next step would be to allocate text pages from the bottom of the address space and data pages from the top. We'll get some fragmentation due to the mix of `RW-` and `R--` data pages, but text pages should all coalesce. After that we could look at reserving permission-based bins within the reserved address space. E.g. if we used 1Mb bins (where all pages within the bin share permissions) then a 4Gb reservation should be able to be covered with 4096 pages.

**Comment by gbaraldi** [comment]
Something like that, I was thinking of doing something like 4mb chunks that you write text from top to the bottom and data from bottom to top. 
I haven't checked if the OS coalesces the adjacent mappings but if yes then it shouldn't be too unreasonable

**Comment by Sh0g0-1758** [comment]
Hi @gbaraldi! I am new to LLVM and would like to work on this issue. Can you please assign it to me.

**Comment by vchuravy** [comment]
@Sh0g0-1758 feel free to work on it, but it won't be officially assigned to you. If you come up with a solution you can open a PR and mention this issue

**Comment by Icenowy** [comment]
This should be fixed in master by #81943 (I found this problem during testing of Mesa LLVMPipe's ORCJIT backend), however I don't think this has been backported to any stable releases yet.

**Comment by giordano** [comment]
@Icenowy I just built julia with its llvm version plus a backport of #81943 and I still see the issue reported above (running some tests ends up generating too many mmaps), so that's not enough for us.

**Comment by Icenowy** [comment]
> @Icenowy I just built julia with its llvm version plus a backport of #81943 and I still see the issue reported above (running some tests ends up generating too many mmaps), so that's not enough for us.

So does this enhance things? In the case of ORCJIT it at least allows me to finish OpenGL ES CTS.

**Comment by giordano** [comment]
@gbaraldi told me we don't deallocate mappings

**Comment by lhames** [comment]
@shivam-dhir Sounds great!

Based on @gbaraldi's first comment:
> First seen in https://github.com/JuliaLang/julia/pull/49745, but to summarize, InProcessMemoryMapper calls mprotect many many times on mmaped memory, so many times that for a non trivial workload we go past /proc/sys/vm/max_map_count leading to a ENOMEM error.
I think this is probably a problem with striped permissions. In that case the fix that @Icenowy mentioned (while being important) won't fix the underlying issue.

We currently allocate all "segments" (permission-grouped bits) sequentially, so in a JIT session with many objects the memory layout will look something like:
```
|R--|R-X|R-W|R--|R-X|RW-|R--|R-X|RW-|... 
 \_________/ \_________/ \_________/
  Object #1   Object #2   Object #3
```
What we really want is something like:
```
|R--|R--|R--|R--|....|R-X|R-X|R-X|R-X|...|RW-|RW-|RW-|RW-|...
 \__________________/ \_________________/ \_________________/
  RO: 1,2,3,...        RX: 1,2,3,...         RW: 1,2,3,...
```

We don't know exactly how much R-- / RW- / R-X memory we'll need up front, so we can't pre-assign these ranges exactly, but there's a couple of compromises we could make:

1. Reserve chunks of a given size for each permission and just stripe the chunks, allocating segments out of available chunks where possible and allocating a new chunk otherwise. For a 2Gb reserved range (assuming that it's aligned) and 4Mb chunks that'd mean at most 512 different mappings.

2. Hybrid scheme: Allocate data from the top of the reserved range, text (R-X) from the bottom, with striped chunks for data (to distinguish `R--` / `R-W`). This would minimize the distinct page table entries needed for text, and if either RO or RW data dominate (probably the common case). then it should keep the entries needed for data low too.

**Comment by lhames** [comment]
I've copied the comment above into https://github.com/llvm/llvm-project/issues/191727, and posted that bug in https://github.com/llvm/llvm-project/issues/189354#issuecomment-4175250637. This is still a nice open project for anyone who wants to take a look.

**Comment by Icenowy** [comment]
Ah, @lhames , do you mean April 2026 in #191727 ?

**Comment by lhames** [comment]
> Ah, [@lhames](https://github.com/lhames) , do you mean April 2026 in [#191727](https://github.com/llvm/llvm-project/issues/191727) ?

Yep -- thanks for catching that! :)
