### ISSUE TITLE
Error installing clang-format from llvm-toolchain-focal

### ISSUE THREAD

**Issue by chouetz** [llvm/llvm-project#64120]
Hello,
Since July 25th afternoon, I have a trouble installing clang-format from llvm-toolchain-focal source list.
On ubuntu 20.04, the error is the following:
```
sudo apt-get -t llvm-toolchain-focal install -y --no-install-recommends \
>     clang-format
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-format : Depends: clang-format-17 (>= 17~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I've checked in the `Packages` file on [llvm repository](https://apt.llvm.org/focal/dists/llvm-toolchain-focal/main/binary-amd64/) and the definition of `clang-format` is the following:
```
Package: clang-format
Source: llvm-defaults (0.58~exp1~20230129223711.13)
Version: 1:17.0-58~exp1~20230129223711.13
Architecture: amd64
Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
Installed-Size: 33
Depends: clang-format-17 (>= 17~)
Breaks: clang (<< 1:3.6-28)
Replaces: clang (<< 1:3.6-28)
Multi-Arch: same
Priority: optional
Section: devel
Filename: pool/main/l/llvm-defaults/clang-format_17.0-58~exp1~20230129223711.13_amd64.deb
Size: 9992
SHA256: 955cd5eeff89955e43b4b31f8819b75afb4ad08e6aa9d4878e68d50230675d6a
SHA1: 89adf563aeec5544fddbacfd6b7c9dde221b3ed3
MD5sum: a743e1bf067cd088bbd80b0c5fe60fe6
```
Whereas `clang-format-17` is not (or no more) available in this repo, but clang-format-18 since yesterday [it seems](https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commit/bf100602e2911e4a996220551c67c8d9616eb2e5)

I installed instead `clang-format-18`. Do you think there is a real issue here?

Many thanks in advance

**Comment by firewave** [comment]
It seems all the packages for some reason recently dropped the `-17` postfix. I am getting the following error for all packages:
```
Package clang-17 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

On a local install I also saw that the `clang` package (which is the default repo one) with updated to a 17.x version.

```
apt list -a clang
Listing... Done
clang/unknown,now 1:17.0-58~exp1~20230726084912.14 amd64 [installed,automatic]
clang/focal 1:10.0-50~exp1 amd64
```

```
apt list -a clang-17
Listing... Done
clang-17/now 1:17~++20230722053003+af32e51a43fb-1~exp1~20230722173124.706 amd64 [installed,local]
```

**Comment by igagis** [comment]
Seeing same issue with Debian Bullseye, Ubuntu Jammy and Ubuntu Focal

https://github.com/cppfw/morda/actions/runs/5670335114/job/15390392591

**Comment by firewave** [comment]
This is even further broken now:
```
+ apt-get install -y clang-16 lldb-16 lld-16 clangd-16
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-lldb-14 : Conflicts: python3-lldb-x.y
 python3-lldb-16 : Conflicts: python3-lldb-x.y
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by firewave** [comment]
CC @sylvestre

**Comment by sylvestre** [comment]
snapshot is now 18, 17 is in a new branch.

Not sure what is causing this. I will have a look (but my connection is pretty bad right now)

**Comment by sylvestre** [comment]
ok, i think i found the issue, the default packages were still pointing to 17
Seems that a patch was missing. I retriggered the build. it should be fixed in less than an hour
sorry about that :(

**Comment by firewave** [comment]
Thanks for the fast reply. Will check later.

**Comment by sylvestre** [comment]
As temporary workaround, installing the branch -17 should fix the issue:

deb http://apt.llvm.org/focal/ llvm-toolchain-focal-17 main

**Comment by igagis** [comment]
@sylvestre it is now fixed for ubuntu focal, but still fails for ubuntu jammy and debian bullseye

**Comment by igagis** [comment]
now works for ubuntu jammy, debian bullseye still fails

**Comment by firewave** [comment]
The versioned clang 17 packages are available again.

But there is still a version-less package made available:
```
clang/unknown 1:18.0-58~exp1~20230727113816.15 amd64 [upgradable from: 1:17.0-58~exp1~20230726084912.14]
clang/now 1:17.0-58~exp1~20230726084912.14 amd64 [installed,upgradable to: 1:18.0-58~exp1~20230727113816.15]
clang/focal 1:10.0-50~exp1 amd64
```

And the "unmnt dependency" issue still perists:
```
+ apt-get install -y clang-17 lldb-17 lld-17 clangd-17
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-lldb-14 : Conflicts: python3-lldb-x.y
 python3-lldb-17 : Conflicts: python3-lldb-x.y
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by igagis** [comment]
@sylvestre still not working

https://github.com/cppfw/morda/actions/runs/5670335114/job/15407959241

**Comment by sylvestre** [comment]
@asl seems that our server hard drive is full
Probably because of  17 added
Could you please add more space? Thanks

**Comment by asl** [comment]
Tagging @sqlbyme

**Comment by binarymaster** [comment]
ReactOS build on Linux/clang has been broken by this, looking for help.

https://github.com/reactos/reactos/actions/runs/5690122270/job/15422895859

```
+ apt-get install -y clang-13 lldb-13 lld-13 clangd-13
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-lldb-13 : Conflicts: python3-lldb-x.y
 python3-lldb-14 : Conflicts: python3-lldb-x.y
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Error: Process completed with exit code 100.
```

**Comment by igagis** [comment]
Debian bullseye still not working

**Comment by sylvestre** [comment]
Ping @asl the sync
All the sync are failing in cp: cannot create regular file ‘/data/apt/www/bullseye.back/pool/main/l/llvm-toolchain-16/mlir-16-tools_16.0.6~++20230710041823+7cbf1a259152-1~exp1~20230710161844.102_arm64.deb’: No space left on device

**Comment by sylvestre** [comment]
@tlattner do you know who could help with it?

**Comment by sqlbyme** [comment]
Hi, I know @asl is working on expanding the volume to get this working
again. Hope to have this up and running correctly again soon. Thanks for
your patience.

Best,
Mike

**Comment by asl** [comment]
Sorry for delay. I think this should be fixed as of now. @sylvestre please check!

**Comment by binarymaster** [comment]
Looks like it's fixed now, our builders are green again, thank you 🙂

**Comment by igagis** [comment]
Installing `clang-format` and `clang-tidy` on Debian Bullseye still fails

https://github.com/cppfw/morda/actions/runs/5691502977/job/15613423935

**Comment by firewave** [comment]
It seems like no packages have been published yet since the issues started:
```
clang-18/unknown,now 1:18~++20230726052612+6971b83b2fdd-1~exp1~20230726172632.710 amd64 [installed,automatic]
```

There was also no new data downloaded from the repos with `apt-get update` supporting this.

**Comment by firewave** [comment]
New packages have been published to the repos:
```
clang-18/unknown,now 1:18~++20230805052926+3e2ed5701b7e-1~exp1~20230805173043.721 amd64 [installed,automatic]
```

It seems the unversioned packages are still being generated. Will file a separate ticket about it later.

**Comment by igagis** [comment]
Debian Bullseye works now. Thank you!

**Comment by sylvestre** [comment]
Thanks
