### ISSUE TITLE
[bug] error: unable to execute command: Aborted

### ISSUE THREAD

**Issue by elvis-hrvat** [llvm/llvm-project#67452]
I tried to build mullvad-browser using makepkg.
Then I got an "error: unable to execute command: Aborted (core dumped)" and the build stopped. Is this a bug in LLVM?
[stdout.log](https://github.com/llvm/llvm-project/files/12729794/stdout.log)
[journal.log](https://github.com/llvm/llvm-project/files/12729809/journal.log)

**Comment by dtcxzyw** [comment]
Seems like you are trying to build for the target that doesn't support AES-NI extension.
Duplicate of #53097

**Comment by elvis-hrvat** [comment]
My CPU is an Intel Core i5-4440. There is `aes` in `/proc/cpuinfo` `flags`, is this not good enough?

**Comment by dtcxzyw** [comment]
> My CPU is an Intel Core i5-4440. There is `aes` in `/proc/cpuinfo` `flags`, is this not good enough?

Maybe rustc didn't pass `target-features=+aes` to LLVM. See also #53097 and #54055.
It has been fixed by https://github.com/rust-lang/rust/pull/94579. Could you please try to build mullvad-browser with the latest rustc? You were using an old version of the rust toolchain (rustc 1.60.0 (7737e0b5c 2022-04-04)).

**Comment by elvis-hrvat** [comment]
I removed target-cpu=native from RUSTFLAGS and replaced march=native with march=x86-64 in CFLAGS and CXXFLAGS and the build was successful.
However, if I change only RUSTFLAGS, the build still fails.
Is this a bug not only in rustc but also in llvm's C++ compiler?

**Comment by elvis-hrvat** [comment]
> I removed `target-cpu=native` from RUSTFLAGS and replaced `march=native` with `march=x86-64` in CFLAGS and CXXFLAGS and the build was successful. However, if I change only RUSTFLAGS, the build still fails. Is this a bug not only in rustc but also in llvm's C++ compiler?

**Comment by phoebewang** [comment]
Clang doesn't allow `target-cpu=native`:
```
$ clang foo.c -Xclang -target-cpu -Xclang native -S -o -
error: unknown target CPU 'native'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, raptorlake, meteorlake, arrowlake, arrowlake-s, lunarlake, gracemont, sierraforest, grandridge, graniterapids, graniterapids-d, emeraldrapids, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, znver4, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
```
