### ISSUE TITLE
Installing llvm stuff right now fails with apt saying v19 is not installable (wondering if this is just a transient issue)

### ISSUE THREAD

**Issue by ykoehler** [llvm/llvm-project#79483]
$ sudo apt install lldb clang-format
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-format : Depends: clang-format-19 (>= 19~) but it is not installable
 lldb : Depends: lldb-19 (>= 19~) but it is not installable
E: Unable to correct problems, you have held broken packages.

This is using 

sudo add-apt-repository -y 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'

on Ubuntu 20.04 LTS.

**Comment by sylvestre** [comment]
yeah, it is the migration from 18 => 19
Should be fixed in a few hours

**Comment by prj-** [comment]
@sylvestre, any update, please? Looks like everything is stuck to last week as well for Debian, cf. https://apt.llvm.org/unstable/pool/main/l/.

**Comment by sylvestre** [comment]
I have been working on it.

**Comment by sylvestre** [comment]
I think it is now fixed

**Comment by prj-** [comment]
I don't know about op, but it sure is fixed on my end. Thank you!

**Comment by gdevenyi** [comment]
This is still broken on a fresh jammy install with the 3 jammy repos enabled:

```
$ cat /etc/apt/sources.list.d/llvm.sources 
X-Repolib-Name: llvm
URIs: http://apt.llvm.org/jammy/
Suites: llvm-toolchain-jammy llvm-toolchain-jammy-17 llvm-toolchain-jammy-18
Components: main
Architectures: amd64
Signed-By: /etc/apt/keyrings/llvm.asc
Types: deb
```

```
sudo apt-get install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) lldb-19:amd64 < none -> 1:19~++20240302031240+1f613bce19ea-1~exp1~20240302151406.1532 @un puN Ib >
Broken lldb-19:amd64 Depends on python3-lldb-19:amd64 < none @un pH >
  Considering python3-lldb-19:amd64 1 as a solution to lldb-19:amd64 0
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lldb-19 : Depends: python3-lldb-19 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by sylvestre** [comment]
@gdevenyi please open a new bug. it isn't probably the same issue
thanks
