### ISSUE TITLE
[SLP] Assertion "Packing must reduce size of vector type." failed

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#80027]
[tc_sztti.tar.gz](https://github.com/llvm/llvm-project/files/14101041/tc_sztti.tar.gz)

opt -mtriple=s390x-unknown-linux -mcpu=z14 tc_sztti.ll -O3 -o /dev/null -S

The SystemZ assertion triggers, as the dst size is bigger than that of src, which does not make sense for a truncate:

```
  assert(SrcTy->getPrimitiveSizeInBits().getFixedValue() >
             DstTy->getPrimitiveSizeInBits().getFixedValue() &&
         "Packing must reduce size of vector type.");
```

```
(gdb) p SrcTy->dump()
<8 x i16>
$5 = void
(gdb) p DstTy->dump()
<8 x i32>
$6 = void
```

`#15 0x00000000038b3891 llvm::SLPVectorizerPass::vectorizeHorReduction(`

@alexey-bataev @Enna1

**Comment by alexey-bataev** [comment]
Looks like I already have a patch for this, hope to fix it soon

**Comment by alexey-bataev** [comment]
Fixed in 285bc69846e76af805cd106ea3ea538a12f5c9b6

**Comment by JonPsson1** [comment]
[tc_crash1_aftercreduce.ll.tar.gz](https://github.com/llvm/llvm-project/files/14750790/tc_crash1_aftercreduce.ll.tar.gz)

still here, it seems:

opt -mtriple=systemz-unknown -mcpu=z15 ./tc_crash1_aftercreduce.ll -O3

"Packing must reduce size of vector type."' failed.
#19 0x000002aa01d53ca8 llvm::SLPVectorizerPass::vectorizeChainsInBlock
...

@alexey-bataev

**Comment by alexey-bataev** [comment]
Fixed in 54ca1e2c041a3780eca83549d7f7137581d32abb

**Comment by JonPsson1** [comment]
Still seeing this...

[tc_slp_crash.ll.tar.gz](https://github.com/llvm/llvm-project/files/14837522/tc_slp_crash.ll.tar.gz)

`opt -mtriple=s390x-unknown-linux -mcpu=z15 -O3 -S -o /dev/null tc_slp_crash.ll`

```
Assertion "Packing must reduce size of vector type."' failed.
...
#18 0x000002aa01d6f400 llvm::SLPVectorizerPass::vectorizeRootInstruction()
```

@alexey-bataev

**Comment by alexey-bataev** [comment]
Hi, thanks for the report. All these crashes have the same symptom but different reasons. May I ask you next time just create the new issue instead of reopening this one? Much easier to track them.

**Comment by alexey-bataev** [comment]
Fixed in 9cb7dffa88190c36db0dc49a7dd2b67e0a44f97e
