### ISSUE TITLE
The llvm-18 Ubuntu Jammy (22.04) LTS binary packages don't include LLVMgold.so

### ISSUE THREAD

**Issue by joshuaehill** [llvm/llvm-project#87553]
The llvm-18 release binary packages for Ubuntu Jammy (22.04) published on the [LLVM Debian/Ubuntu nightly packages](https://apt.llvm.org/) don't seem to include the LLVMgold.so plugin required for LTO support.

In prior versions, this was included in the linker-tools package, but this file is not presently included in the llvm-18-linker-tools package.

Using the current package set for llvm-18 when using LTO, the linker complains:
`/usr/bin/ld: /usr/lib/llvm-18/bin/../lib/LLVMgold.so: error loading plugin: /usr/lib/llvm-18/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory`

**Comment by joshuaehill** [comment]
This seems to have been [mentioned before](https://github.com/llvm/llvm-project/issues/84271#issuecomment-2016467829), and may be related to #84271.

**Comment by MaskRay** [comment]
Thanks for the report. I created https://github.com/llvm/llvm-project/pull/87567

**Comment by sylvestre** [comment]
this is me and now, we don't use LLVM_INSTALL_TOOLCHAIN_ONLY
grep on https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/18/debian/rules return 0

**Comment by MaskRay** [comment]
I confirm that the llvm-17-linker-tools package contains `LLVMgold.so` while llvm-18-linker-tools doesn't.

Landed #87567 to install `LLVMgold.so` (like we install libLTO.so) in LLVM_INSTALL_TOOLCHAIN_ONLY=on builds but @sylvestre said it might be unrelated?

https://apt.llvm.org/mantic/pool/main/l/llvm-toolchain-17/llvm-17-linker-tools_17.0.6~%2B%2B20240124120726%2B6009708b4367-1~exp1~20240124120743.47_amd64.deb
```
% tar tvf data.tar.zst
drwxr-xr-x root/root         0 2024-01-24 04:07 ./
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/lib/
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/lib/bfd-plugins/
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/lib/llvm-17/
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/lib/llvm-17/lib/
-rw-r--r-- root/root   4021888 2024-01-24 04:07 ./usr/lib/llvm-17/lib/LLVMPolly.so
-rw-r--r-- root/root     89848 2024-01-24 04:07 ./usr/lib/llvm-17/lib/LLVMgold.so
-rw-r--r-- root/root     69576 2024-01-24 04:07 ./usr/lib/llvm-17/lib/libLTO.so.17
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/share/
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/share/doc/
drwxr-xr-x root/root         0 2024-01-24 04:07 ./usr/share/doc/llvm-17-linker-tools/
-rw-r--r-- root/root     35092 2024-01-24 04:07 ./usr/share/doc/llvm-17-linker-tools/changelog.Debian.gz
-rw-r--r-- root/root      6897 2024-01-24 04:07 ./usr/share/doc/llvm-17-linker-tools/copyright
lrwxrwxrwx root/root         0 2024-01-24 04:07 ./usr/lib/bfd-plugins/LLVMgold-17.so -> ../llvm-17/lib/LLVMgold.so
```


https://apt.llvm.org/mantic/pool/main/l/llvm-toolchain-18/llvm-18-linker-tools_18.1.3~%2B%2B20240322073236%2Bef6d1ec07c69-1~exp1~20240322193248.98_amd64.deb
```
% tar tvf data.tar.zst
drwxr-xr-x root/root         0 2024-03-22 12:32 ./
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/lib/
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/lib/bfd-plugins/
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/lib/llvm-18/
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/lib/llvm-18/lib/
-rw-r--r-- root/root   3973096 2024-03-22 12:32 ./usr/lib/llvm-18/lib/LLVMPolly.so
-rw-r--r-- root/root     70328 2024-03-22 12:32 ./usr/lib/llvm-18/lib/libLTO.so.18.1
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/share/
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/share/doc/
drwxr-xr-x root/root         0 2024-03-22 12:32 ./usr/share/doc/llvm-18-linker-tools/
-rw-r--r-- root/root     36840 2024-03-22 12:32 ./usr/share/doc/llvm-18-linker-tools/changelog.Debian.gz
-rw-r--r-- root/root      6897 2024-03-22 12:32 ./usr/share/doc/llvm-18-linker-tools/copyright
lrwxrwxrwx root/root         0 2024-03-22 12:32 ./usr/lib/bfd-plugins/LLVMgold-18.so -> ../llvm-18/lib/LLVMgold.so
```

**Comment by Explorer09** [comment]
I was about to report the similar issue to Debian packages, because this affects my CI build as well ([see this build log](https://github.com/Explorer09/htop-1/actions/runs/8390820638/job/23049256024)). Now I cannot use LLVM-18 with LTO anymore.

By the way, the fastest way to verify this is to see this page:
https://packages.debian.org/sid/amd64/llvm-18-linker-tools/filelist
and compare with this:
https://packages.debian.org/sid/amd64/llvm-17-linker-tools/filelist
or this:
https://packages.debian.org/experimental/amd64/llvm-19-linker-tools/filelist

And see the `LLVMgold.so` file is missing.

**Comment by MaskRay** [comment]
@sylvestre ^^

**Comment by sylvestre** [comment]
yeah, it is now fixed.
I tried to build llvm-toolchain with mold and it caused llvmgold not to be generated?! 
@MaskRay do you think it is a LLVM bug ?

**Comment by Explorer09** [comment]
Can you guys tell us which version of the package will start including LLVMgold.so back? Because I need to estimate when the llvm-18 build in GitHub Actions CI will work again with LTO.

[llvm-18-linker-tools_18.1.3~%2B%2B20240322073153%2Bef6d1ec07c69-1~exp1~20240322193300.86_amd64](https://apt.llvm.org/jammy/pool/main/l/llvm-toolchain-18/llvm-18-linker-tools_18.1.3~%2B%2B20240322073153%2Bef6d1ec07c69-1~exp1~20240322193300.86_amd64.deb) surely doesn't have the LLVMgold.so.

**Comment by sylvestre** [comment]
> Can you guys tell us which version of the package will start including LLVMgold.so back? Because I need to estimate when the llvm-18 build in GitHub Actions CI will work again with LTO.
> 
> [llvm-18-linker-tools_18.1.3~%2B%2B20240322073153%2Bef6d1ec07c69-1~exp1~20240322193300.86_amd64](https://apt.llvm.org/jammy/pool/main/l/llvm-toolchain-18/llvm-18-linker-tools_18.1.3~%2B%2B20240322073153%2Bef6d1ec07c69-1~exp1~20240322193300.86_amd64.deb) surely doesn't have the LLVMgold.so.

i retriggered this build for 18, it should be available in a few hours

**Comment by yujincheng08** [comment]
@sylvestre hi, can you also fix ubuntu 24.04 support? See #90536

**Comment by clundquist-stripe** [comment]
@yujincheng08 
`libclang-rt-dev` provides these libraries on 24.04
I think it is a meta package for https://packages.ubuntu.com/eu/noble/libdevel/libclang-rt-18-dev specifically as of this writing.

**Comment by TonyXiang8787** [comment]
> @yujincheng08 `libclang-rt-dev` provides these libraries on 24.04 I think it is a meta package for https://packages.ubuntu.com/eu/noble/libdevel/libclang-rt-18-dev specifically as of this writing.

@clundquist-stripe I have tried to install `libclang-rt-18-dev` in Ubuntu 24.04. It still does not contain `LLVMgold.so`.

**Comment by MaskRay** [comment]
https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-18/+bug/2064187 ("llvm-18-linker-tools does not include LLVMgold.so") seems related.

**Comment by sylvestre** [comment]
@MaskRay indeed :/ this is the autosync from Debian to Ubuntu. I am following up with Ubuntu to get a fix as noble is a LTS

**Comment by illwieckz** [comment]
I don't know if it's fixed for Ubuntu Jammy 22.04, but I confirm this is not fixed yet for Mantis 23.10:

- https://github.com/llvm/llvm-project/issues/90810

**Comment by Explorer09** [comment]
Ubuntu Jammy (22.04) now has an updated `llvm-linker-tools` package since May 15th, 2024.

**Comment by sylvestre** [comment]
thanks for confirming, i fixed the various issues

**Comment by tingsi5** [comment]
@sylvestre For some reasons, the LLVMgold.so is still not included in the package of riscv64 for noble ([link](https://launchpad.net/ubuntu/+archive/primary/+files/llvm-18-linker-tools_18.1.3-1ubuntu1_riscv64.deb)), any ideas?

```
$ dpkg -c ~/Downloads/llvm-18-linker-tools_18.1.3-1ubuntu1_riscv64.deb 
drwxr-xr-x root/root         0 2024-05-27 16:26 ./
drwxr-xr-x root/root         0 2024-05-27 16:26 ./usr/
drwxr-xr-x root/root         0 2024-05-27 16:26 ./usr/lib/
drwxr-xr-x root/root         0 2024-05-27 16:26 ./usr/lib/llvm-18/
drwxr-xr-x root/root         0 2024-05-27 16:26 ./usr/lib/llvm-18/lib/
-rw-r--r-- root/root   3312944 2024-05-27 16:26 ./usr/lib/llvm-18/lib/LLVMPolly.so
-rw-r--r-- root/root     56984 2024-05-27 16:26 ./usr/lib/llvm-18/lib/libLTO.so.18.1
drwxr-xr-x root/root         0 2024-05-27 16:26 ./usr/share/
drwxr-xr-x root/root         0 2024-05-27 16:26 ./usr/share/doc/
drwxr-xr-x root/root         0 2024-05-27 16:26 ./usr/share/doc/llvm-18-linker-tools/
-rw-r--r-- root/root      6897 2024-03-20 16:18 ./usr/share/doc/llvm-18-linker-tools/copyright
lrwxrwxrwx root/root         0 2024-05-27 16:26 ./usr/share/doc/llvm-18-linker-tools/changelog.Debian.gz -> ../libllvm18/changelog.Debian.gz
```

**Comment by mologie** [comment]
@tingsi5 There was a related question in the [Ubuntu bug of this issue](https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-18/+bug/2064187), where a comment notes that Gold/binutils lacks riscv64 support upstream, hence the extension is not build either.

**Comment by topperc** [comment]
> @tingsi5 There was a related question in the [Ubuntu bug of this issue](https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-18/+bug/2064187), where a comment notes that Gold/binutils lacks riscv64 support upstream, hence the extension is not build either.

Despite the file being named LLVMgold.so, the bfd linker in binutils implements the same plugin interface and can use it. Historically, I think the plugin interface was supported by gold first and added to bfd later.
