### ISSUE TITLE
lldb/source/Core/Debugger.cpp:2069: Clumsy string resize ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#91209]
Static analyser cppcheck says:

lldb/source/Core/Debugger.cpp:2069:15: performance: Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]

Source code is

    message = message.substr(0, term_width - ellipsis);

**Comment by vedantbarve** [comment]
@JOE1994 can you please assign this task to me?

**Comment by aabhinavg** [comment]
Hi @vedantbarve Are you currently working on it?

**Comment by vedantbarve** [comment]
I wanted to make my first contribution to LLVM through this PR. Since @aabhinavg had self-assigned it, I took up some other work. I will get free in 3-4 days. @JOE1994 @aabhinavg If you guys are okay with it, can I please complete this issue in a few days?

**Comment by Dinistro** [comment]
No idea what happened here. I did not actively interact with the linked PR, not is the linked commit there from me. either some weird GitHub issue or a hash collision?

**Comment by bulbazord** [comment]
> No idea what happened here. I did not actively interact with the linked PR, not is the linked commit there from me. either some weird GitHub issue or a hash collision?

Github indicates that you merged the relevant PR.

**Comment by Dinistro** [comment]
> > No idea what happened here. I did not actively interact with the linked PR, not is the linked commit there from me. either some weird GitHub issue or a hash collision?
> 
> Github indicates that you merged the relevant PR.

I pushed a commit directly to master at that point in time. If you look at the referred commit in the linked PR, it's visible that someone else is the author. Odd.

**Comment by shakedechn** [comment]
I see the issue still exists. May I take it as my first issue?

**Comment by shakedechn** [comment]
I see this issue still exists. One PR was opened for it without progress since May. May I take this issue?
