### ISSUE TITLE
Can no longer build using the latest nightly debian build

### ISSUE THREAD

**Issue by lerno** [llvm/llvm-project#92359]
Using the latest build from http://apt.llvm.org/focal/ (`1:19~++20240514053206+86f655cb4e2f-1~exp1~20240514173349.1024`), compilation runs into the following error:

```
CMake Error at /usr/lib/llvm-19/lib/cmake/llvm/LLVMExports.cmake:1891 (message):
  The imported target "LibcTableGenUtil" references the file

     "/usr/lib/llvm-19/lib/libLibcTableGenUtil.a"
-- Configuring incomplete, errors occurred!

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-19/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/llvm-19/cmake/LLVMConfig.cmake:373 (include)
  CMakeLists.txt:123 (find_package)
  ```
  
  Previous version (`1:19~++20240421052952+48324f0f7b26-1~exp1~20240421173100.1000`) worked fine.

**Comment by anutosh491** [comment]
Thanks for reporting this. I ran into the same error some time back. Hopefully can be resolved soon.

**Comment by sylvestre** [comment]
should be fixed now (depending on the CDN caches)

**Comment by anutosh491** [comment]
My commit would trying the same still fails https://github.com/symengine/symengine/actions/runs/9127183905/job/25096950338?pr=2016 with the above error.

**Comment by dtcxzyw** [comment]
The following workaround works for me:
```
sudo touch /usr/lib/llvm-19/lib/libLibcTableGenUtil.a
```

**Comment by sylvestre** [comment]
fixed for real now

**Comment by lerno** [comment]
Can confirm it works.

**Comment by sylvestre** [comment]
thanks!

**Comment by lerno** [comment]
Thank you for fixing it!

**Comment by anutosh491** [comment]
Yes. Thanks for fixing it :)

**Comment by samvv** [comment]
Actually I'm getting other issues as well. This is probably another issue.

**Comment by Zingam** [comment]
I and experiencing the same as of today too.

**Comment by Zingam** [comment]
> sudo touch /usr/lib/llvm-19/lib/libLibcTableGenUtil.a

That doesn't work right now on WSL Ubuntu 24.04 and `llvm.sh 19`.

> please open a new bug with the detailed info

@sylvestre I created a bug report https://github.com/llvm/llvm-project/issues/99819. I decided to try the "workaround" from above and I get now:

[cmake] CMake Error at /usr/lib/llvm-19/lib/cmake/clang/ClangTargets.cmake:844 (message):
[cmake]   The imported target "clangBasic" references the file
[cmake] 
[cmake]      "/usr/lib/llvm-19/lib/libclangBasic.a"
[cmake] 
[cmake]   but this file does not exist.  Possible reasons include:
[cmake] 
[cmake]   * The file was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and contained
[cmake] 
[cmake]      "/usr/lib/llvm-19/lib/cmake/clang/ClangTargets.cmake"

Is it possible to workaround these? Or this needs to be fixed?

**Comment by emmenlau** [comment]
I am getting this issue on Ubuntu 24.04 (with latest updates from today) and `llvm-19` version `19.1.0~++20240826073408+5f744ee5c770-1~exp1~20240826073423.27`.

**Comment by Zingam** [comment]
> I am getting this issue on Ubuntu 24.04 (with latest updates from today) and `llvm-19` version `19.1.0~++20240826073408+5f744ee5c770-1~exp1~20240826073423.27`.

The new bug report: https://github.com/llvm/llvm-project/issues/99819
