### ISSUE TITLE
reduction-templates.h:94:26: error: a template argument list is expected after a name prefixed by the template keyword

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#94049]
building flang on linux ubuntu mantic on arm64 fails with

```
/build/source/build-llvm/./bin/clang++ -DFLANG_INCLUDE_TESTS=1 -DFLANG_LITTLE_ENDIAN=1 -DFLANG_VENDOR="\"Ubuntu \"" -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/source/build-llvm/tools/clang/stage2-bins/tools/flang/runtime -I/build/source/flang/runtime -I/build/source/flang/include -I/build/source/build-llvm/tools/clang/stage2-bins/tools/flang/include -I/build/source/build-llvm/tools/clang/stage2-bins/include -I/build/source/llvm/include -isystem /build/source/llvm/../mlir/include -isystem /build/source/build-llvm/tools/clang/stage2-bins/tools/mlir/include -isystem /build/source/build-llvm/tools/clang/stage2-bins/tools/clang/include -isystem /build/source/llvm/../clang/include -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -mbranch-protection=standard -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/source/build-llvm/tools/clang/stage2-bins=../../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -Wno-deprecated-copy -Wno-string-conversion -Wno-ctad-maybe-unsupported -Wno-unused-command-line-argument -Wstring-conversion           -Wcovered-switch-default -Wno-nested-anon-types -fno-lto -O2 -DNDEBUG -g1 -std=c++17   -U_GLIBCXX_ASSERTIONS -U_LIBCPP_ENABLE_ASSERTIONS  -fno-exceptions -funwind-tables -MD -MT tools/flang/runtime/CMakeFiles/obj.FortranRuntime.dir/reduction.cpp.o -MF tools/flang/runtime/CMakeFiles/obj.FortranRuntime.dir/reduction.cpp.o.d -o tools/flang/runtime/CMakeFiles/obj.FortranRuntime.dir/reduction.cpp.o -c /build/source/flang/runtime/reduction.cpp
In file included from /build/source/flang/runtime/reduction.cpp:17:
/build/source/flang/runtime/reduction-templates.h:94:26: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   94 |     accumulator.template GetResult();
      |                          ^
/build/source/flang/runtime/reduction-templates.h:101:26: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  101 |     accumulator.template GetResult(&result);
      |                          ^
/build/source/flang/runtime/reduction-templates.h:144:24: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  144 |   accumulator.template GetResult(result, zeroBasedDim);
      |                        ^
/build/source/flang/runtime/reduction-templates.h:172:24: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  172 |   accumulator.template GetResult(result, zeroBasedDim);
      |                        ^
4 errors generated.
```

**Comment by evelez7** [comment]
Looks like these were fixed with #94204

**Comment by sylvestre** [comment]
indeed, thanks

**Comment by morgabm** [comment]
@DavidSpickett I am building with 19.1.0 on windows which has your fix listed above, but I am still getting this error.

```
...\external\atomic_queue\include\atomic_queue/atomic_queue.h(402,24): error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  402 |         Base::template do_push_any(std::forward<U>(element), states_[index], elements_[index]);
      |                        ^
...\external\atomic_queue\include\atomic_queue/atomic_queue.h(396,31): error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  396 |         return Base::template do_pop_any(states_[index], elements_[index]);
      |       
```

**Comment by sylvestre** [comment]
@morgabm please open a new bug
